# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9eedf7b8b1d6075353148286ac5c700b2687f5c9ef493e968287c264b5a12bc1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'json'
require 'html_to_markdown_rb'
