# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9338e457aa2b2a8f2c0a2d5a60b8ca75f6999aea7a6c06857a8eb7c9cd0115f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = "3.5.2"
end
