# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f94527b64db68a5f23ef7f6f5a002fb4129c500d20cc9c076bc8fa24d80a4c7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module HtmlToMarkdown
  VERSION = '3.4.0.pre.rc.43'
end
