# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22cbc7728e7527feef8e06cb67ad8290c07e3c276a312d04d887bbecdf8f6101
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.8.3"
end
