// Generated by alef. Do not edit by hand.
// alef:hash:4ba300ecbb725eb266bbcd4f47e9bc50e560372ba8b6f9d9f93c785e8758cdc8

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-android-e2e"
