<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20ecfea42a0ee961d9ccc3eb2c536813e3870a7b98a8e85e1d741e5d1860a4b0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

// Verify the extension is loaded.
if (!extension_loaded('html_to_markdown')) {
    fwrite(STDERR, "FAIL: html_to_markdown extension is not loaded\n");
    exit(1);
}

// Verify the convert function exists.
if (!function_exists('html_to_markdown_convert')) {
    fwrite(STDERR, "FAIL: html_to_markdown_convert() not found\n");
    exit(1);
}

// Smoke-test: convert a heading.
$result = html_to_markdown_convert('<h1>Hi</h1>');

if (!str_contains($result, 'Hi')) {
    fwrite(STDERR, "FAIL: expected output to contain 'Hi', got: $result\n");
    exit(1);
}

echo "PASS: html_to_markdown_convert('<h1>Hi</h1>') => $result\n";
exit(0);
