<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0bb33f61f6b0fb21b11f0a4a6816b4de0f2a0ab1fc607ebf1ecf2f5cacf7ffea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

// Verify the extension is loaded.
if (!extension_loaded('html_to_markdown')) {
    fwrite(STDERR, "FAIL: html_to_markdown extension is not loaded\n");
    exit(1);
}

// Verify the configured function exists.
if (!function_exists('html_to_markdown_convert')) {
    fwrite(STDERR, "FAIL: html_to_markdown_convert() not found\n");
    exit(1);
}

// Smoke-test the configured function.
$result = html_to_markdown_convert('smoke test');

if ($result === null) {
    fwrite(STDERR, "FAIL: expected non-null result\n");
    exit(1);
}

echo "PASS: html_to_markdown_convert() returned a non-null result\n";
exit(0);
