<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3478a445458a33d08bd86006e3bd2435c28bc2078c46d33f758971cc085f89ca
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

// Verify the extension is loaded.
if (!extension_loaded('html_to_markdown')) {
    fwrite(STDERR, "FAIL: html_to_markdown extension is not loaded\n");
    exit(1);
}

// Verify the configured function exists.
if (!function_exists('html_to_markdown_convert')) {
    fwrite(STDERR, "FAIL: html_to_markdown_convert() not found\n");
    exit(1);
}

// Smoke-test the configured function.
$result = html_to_markdown_convert('smoke test');

if ($result === null) {
    fwrite(STDERR, "FAIL: expected non-null result\n");
    exit(1);
}

echo "PASS: html_to_markdown_convert() returned a non-null result\n";
exit(0);
