# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a583f5fb46423d57efaae4c71b9f4d9435fd39a9d583f4c86c7f0cf5974932e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: conversion
defmodule E2e.ConversionTest do
  use ExUnit.Case, async: false

  describe "blockquote_multiple_paragraphs" do
    @tag :skip
    test "blockquote_multiple_paragraphs" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "blockquote_nested" do
    @tag :skip
    test "blockquote_nested" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "blockquote_simple" do
    @tag :skip
    test "blockquote_simple" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "blockquote_with_list" do
    @tag :skip
    test "blockquote_with_list" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "bold_and_italic" do
    @tag :skip
    test "bold_and_italic" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "bold_strong" do
    @tag :skip
    test "bold_strong" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "code_block" do
    @tag :skip
    test "code_block" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "code_block_no_language" do
    @tag :skip
    test "code_block_no_language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "code_inline_in_paragraph" do
    @tag :skip
    test "code_inline_in_paragraph" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "code_with_backticks_in_content" do
    @tag :skip
    test "code_with_backticks_in_content" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "emphasis_mark_highlight" do
    @tag :skip
    test "emphasis_mark_highlight" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "emphasis_strikethrough_del" do
    @tag :skip
    test "emphasis_strikethrough_del" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "emphasis_strikethrough_s" do
    @tag :skip
    test "emphasis_strikethrough_s" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "emphasis_subscript" do
    @tag :skip
    test "emphasis_subscript" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "emphasis_superscript" do
    @tag :skip
    test "emphasis_superscript" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "emphasis_underline_u" do
    @tag :skip
    test "emphasis_underline_u" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "form_input_elements" do
    @tag :skip
    test "form_input_elements" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "form_select_options" do
    @tag :skip
    test "form_select_options" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "form_textarea" do
    @tag :skip
    test "form_textarea" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "heading_h1" do
    @tag :skip
    test "heading_h1" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "heading_h2" do
    @tag :skip
    test "heading_h2" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "heading_h3" do
    @tag :skip
    test "heading_h3" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "heading_h4" do
    @tag :skip
    test "heading_h4" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "heading_h5" do
    @tag :skip
    test "heading_h5" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "heading_h6" do
    @tag :skip
    test "heading_h6" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "image_figure_figcaption" do
    @tag :skip
    test "image_figure_figcaption" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "image_linked" do
    @tag :skip
    test "image_linked" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "image_no_alt" do
    @tag :skip
    test "image_no_alt" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "image_simple" do
    @tag :skip
    test "image_simple" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "image_with_title" do
    @tag :skip
    test "image_with_title" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "inline_code" do
    @tag :skip
    test "inline_code" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "italic_em" do
    @tag :skip
    test "italic_em" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "line_break_br_tag" do
    @tag :skip
    test "line_break_br_tag" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "line_break_hr_tag" do
    @tag :skip
    test "line_break_hr_tag" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "line_break_multiple_br" do
    @tag :skip
    test "line_break_multiple_br" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_anchor_fragment" do
    @tag :skip
    test "link_anchor_fragment" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_empty_href" do
    @tag :skip
    test "link_empty_href" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_image_inside" do
    @tag :skip
    test "link_image_inside" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_mailto" do
    @tag :skip
    test "link_mailto" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_simple" do
    @tag :skip
    test "link_simple" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_with_bold_text" do
    @tag :skip
    test "link_with_bold_text" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "link_with_title" do
    @tag :skip
    test "link_with_title" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_definition_dl" do
    @tag :skip
    test "list_definition_dl" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_item_multiple_paragraphs" do
    @tag :skip
    test "list_item_multiple_paragraphs" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_mixed_nested" do
    @tag :skip
    test "list_mixed_nested" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_nested_ordered" do
    @tag :skip
    test "list_nested_ordered" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_nested_unordered" do
    @tag :skip
    test "list_nested_unordered" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_task_checkboxes" do
    @tag :skip
    test "list_task_checkboxes" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "ordered_list" do
    @tag :skip
    test "ordered_list" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "paragraph_multiple" do
    @tag :skip
    test "paragraph_multiple" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "paragraph_nested_divs" do
    @tag :skip
    test "paragraph_nested_divs" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "paragraph_simple" do
    @tag :skip
    test "paragraph_simple" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "paragraph_with_inline_formatting" do
    @tag :skip
    test "paragraph_with_inline_formatting" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "paragraph_with_line_breaks" do
    @tag :skip
    test "paragraph_with_line_breaks" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_abbr" do
    @tag :skip
    test "semantic_abbr" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_article" do
    @tag :skip
    test "semantic_article" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_definition_list" do
    @tag :skip
    test "semantic_definition_list" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_details_summary" do
    @tag :skip
    test "semantic_details_summary" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_hr" do
    @tag :skip
    test "semantic_hr" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_mark_highlight" do
    @tag :skip
    test "semantic_mark_highlight" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_section_with_heading" do
    @tag :skip
    test "semantic_section_with_heading" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "semantic_sub_superscript" do
    @tag :skip
    test "semantic_sub_superscript" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "simple_table" do
    @tag :skip
    test "simple_table" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_empty" do
    @tag :skip
    test "table_empty" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_no_thead" do
    @tag :skip
    test "table_no_thead" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_pipe_chars_in_content" do
    @tag :skip
    test "table_pipe_chars_in_content" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_with_alignment" do
    @tag :skip
    test "table_with_alignment" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_with_colspan" do
    @tag :skip
    test "table_with_colspan" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "unordered_list" do
    @tag :skip
    test "unordered_list" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
