# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:66d9770e19357c7400d839e31aa1101f10448baf3bed551bc7b7abf228369fc3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: metadata
defmodule E2e.MetadataTest do
  use ExUnit.Case, async: false

  describe "metadata_author_meta" do
    @tag :skip
    test "metadata_author_meta" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_canonical_url" do
    @tag :skip
    test "metadata_canonical_url" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_description_meta" do
    @tag :skip
    test "metadata_description_meta" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_dublin_core" do
    @tag :skip
    test "metadata_dublin_core" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_extract_all_images" do
    @tag :skip
    test "metadata_extract_all_images" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_extract_all_links" do
    @tag :skip
    test "metadata_extract_all_links" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_headers_hierarchy" do
    @tag :skip
    test "metadata_headers_hierarchy" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_keywords_meta" do
    @tag :skip
    test "metadata_keywords_meta" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_lang_attribute" do
    @tag :skip
    test "metadata_lang_attribute" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_microdata_schema_article" do
    @tag :skip
    test "metadata_microdata_schema_article" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_microdata_schema_breadcrumb" do
    @tag :skip
    test "metadata_microdata_schema_breadcrumb" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_microdata_schema_organization" do
    @tag :skip
    test "metadata_microdata_schema_organization" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_microdata_schema_person" do
    @tag :skip
    test "metadata_microdata_schema_person" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_microdata_schema_product" do
    @tag :skip
    test "metadata_microdata_schema_product" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_text_direction_ltr" do
    @tag :skip
    test "metadata_text_direction_ltr" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_text_direction_rtl" do
    @tag :skip
    test "metadata_text_direction_rtl" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "metadata_title_tag" do
    @tag :skip
    test "metadata_title_tag" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "og_basic_tags" do
    @tag :skip
    test "og_basic_tags" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "og_multiple_tags" do
    @tag :skip
    test "og_multiple_tags" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "structured_data_json_ld" do
    @tag :skip
    test "structured_data_json_ld" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "structured_data_multiple_json_ld" do
    @tag :skip
    test "structured_data_multiple_json_ld" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "twitter_card_tags" do
    @tag :skip
    test "twitter_card_tags" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
