packages:
    - crates/html-to-markdown-node
    - crates/html-to-markdown-wasm
    - e2e/node
    - e2e/wasm

onlyBuiltDependencies:
    - esbuild

ignoredBuiltDependencies:
    - wasm-pack

allowBuilds:
    esbuild: true

minimumReleaseAgeExclude:
    - "@xberg-io/html-to-markdown-*"
    - "@xberg-io/html-to-markdown-wasm"
    - "@xberg-io/html-to-markdown"
