// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6edbd6619858eddebfcb13f1219e347f7389820691d902b5ca7b16e58e4bf4b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using HtmlToMarkdown;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: real-world.</summary>
public class RealWorldTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_RealWorldBlogPost()
    {
        // Blog post with headings, paragraphs, code blocks, and links converts to readable Markdown
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_RealWorldDocumentationPage()
    {
        // Documentation page with nested lists, code examples, and blockquotes converts correctly
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_RealWorldProductPage()
    {
        // Product page with table, images, and lists converts correctly
    }
}
