// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b3113b59584aeef5423ebd4d174413aa4af60651d64842ab88495f9e09cb3c32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using HtmlToMarkdown;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: smoke.</summary>
public class SmokeTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeEmptyString()
    {
        // Empty string produces empty output
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeSimpleHeading()
    {
        // H1 heading converts to ATX markdown
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeSimpleParagraph()
    {
        // Simple paragraph converts correctly
    }
}
