# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f7d1a71cc04f429d08683769e9e6397ed815257e2bef9cc8f83a33243717aecb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_empty_string: Empty string produces empty output' do
    result = HtmlToMarkdown.convert('')
    # skipped: field 'content' not applicable for simple result type

  end

  it 'smoke_simple_heading: H1 heading converts to ATX markdown' do
    result = HtmlToMarkdown.convert('<h1>Title</h1>')
    # skipped: field 'content' not applicable for simple result type

  end

  it 'smoke_simple_paragraph: Simple paragraph converts correctly' do
    result = HtmlToMarkdown.convert('<p>Hello World</p>')
    # skipped: field 'content' not applicable for simple result type
    expect(result.to_s).not_to be_empty

  end
end
