// Generated by alef. Do not edit by hand.
// alef:hash:343ebe0b8cb2b70f17247e419c6a21e0940eb11e4428ec2d98aa63d39bd5a9c3
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg.android

/**
 * Heading style options for Markdown output.
 *
 * Controls how headings (h1-h6) are rendered in the output Markdown.
 */
enum class HeadingStyle {
    /** Underlined style (=== for h1, --- for h2). */
    @com.fasterxml.jackson.annotation.JsonProperty("Underlined") UNDERLINED,
    /** ATX style (# for h1, ## for h2, etc.). Default. */
    @com.fasterxml.jackson.annotation.JsonProperty("Atx") ATX,
    /** ATX closed style (# title #, with closing hashes). */
    @com.fasterxml.jackson.annotation.JsonProperty("AtxClosed") ATX_CLOSED;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            UNDERLINED -> "Underlined"
            ATX -> "Atx"
            ATX_CLOSED -> "AtxClosed"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): HeadingStyle =
            when (value) {
                "Underlined",
                "underlined" -> UNDERLINED
                "Atx",
                "atx" -> ATX
                "AtxClosed",
                "atxclosed" -> ATX_CLOSED
                else -> throw IllegalArgumentException("Unknown HeadingStyle value: $value")
            }
    }
}
