// Generated by alef. Do not edit by hand.

package dev.kreuzberg.android

import dev.kreuzberg.htmltomarkdown.HtmlToMarkdownRs as Bridge

/**
 * Document-level metadata extracted from `<head>` and top-level elements.
 *
 * Contains all metadata typically used by search engines, social media platforms,
 * and browsers for document indexing and presentation.
 */
data class DocumentMetadata(
    val title: String?,
    val description: String?,
    val keywords: List<String>,
    val author: String?,
    val canonicalUrl: String?,
    val baseHref: String?,
    val language: String?,
    val textDirection: TextDirection?,
    val openGraph: Map<String, String>,
    val twitterCard: Map<String, String>,
    val metaTags: Map<String, String>
)

/**
 * Header element metadata with hierarchy tracking.
 *
 * Captures heading elements (h1-h6) with their text content, identifiers,
 * and position in the document structure.
 */
data class HeaderMetadata(
    val level: Byte,
    val text: String,
    val id: String?,
    val depth: Long,
    val htmlOffset: Long
)

/**
 * Hyperlink metadata with categorization and attributes.
 *
 * Represents `<a>` elements with parsed href values, text content, and link type classification.
 */
data class LinkMetadata(
    val href: String,
    val text: String,
    val title: String?,
    val linkType: LinkType,
    val rel: List<String>,
    val attributes: Map<String, String>
)

/**
 * Image metadata with source and dimensions.
 *
 * Captures `<img>` elements and inline `<svg>` elements with metadata
 * for image analysis and optimization.
 */
data class ImageMetadata(
    val src: String,
    val alt: String?,
    val title: String?,
    val dimensions: List<Int>?,
    val imageType: ImageType,
    val attributes: Map<String, String>
)

/**
 * Structured data block (JSON-LD, Microdata, or RDFa).
 *
 * Represents machine-readable structured data found in the document.
 * JSON-LD blocks are collected as raw JSON strings for flexibility.
 */
data class StructuredData(
    val dataType: StructuredDataType,
    val rawJson: String,
    val schemaType: String?
)

/**
 * Comprehensive metadata extraction result from HTML document.
 *
 * Contains all extracted metadata types in a single structure,
 * suitable for serialization and transmission across language boundaries.
 */
data class HtmlMetadata(
    val document: DocumentMetadata,
    val headers: List<HeaderMetadata>,
    val links: List<LinkMetadata>,
    val images: List<ImageMetadata>,
    val structuredData: List<StructuredData>
)

/**
 * Main conversion options for HTML to Markdown conversion.
 *
 * Use `ConversionOptions.builder()` to construct, or `the default constructor` for defaults.
 */
data class ConversionOptions(
    val headingStyle: HeadingStyle,
    val listIndentType: ListIndentType,
    val listIndentWidth: Long,
    val bullets: String,
    val strongEmSymbol: String,
    val escapeAsterisks: Boolean,
    val escapeUnderscores: Boolean,
    val escapeMisc: Boolean,
    val escapeAscii: Boolean,
    val codeLanguage: String,
    val autolinks: Boolean,
    val defaultTitle: Boolean,
    val brInTables: Boolean,
    val highlightStyle: HighlightStyle,
    val extractMetadata: Boolean,
    val whitespaceMode: WhitespaceMode,
    val stripNewlines: Boolean,
    val wrap: Boolean,
    val wrapWidth: Long,
    val convertAsInline: Boolean,
    val subSymbol: String,
    val supSymbol: String,
    val newlineStyle: NewlineStyle,
    val codeBlockStyle: CodeBlockStyle,
    val keepInlineImagesIn: List<String>,
    val preprocessing: PreprocessingOptions,
    val encoding: String,
    val debug: Boolean,
    val stripTags: List<String>,
    val preserveTags: List<String>,
    val skipImages: Boolean,
    val linkStyle: LinkStyle,
    val outputFormat: OutputFormat,
    val includeDocumentStructure: Boolean,
    val extractImages: Boolean,
    val maxImageSize: Long,
    val captureSvg: Boolean,
    val inferDimensions: Boolean,
    val maxDepth: Long?,
    val excludeSelectors: List<String>,
    val visitor: VisitorHandle?
)

/**
 * Builder for `ConversionOptions`.
 *
 * All fields start with default values. Call `.build()` to produce the final options.
 */
class ConversionOptionsBuilder {}

/**
 * Partial update for `ConversionOptions`.
 *
 * Uses `Option<T>` fields for selective updates. Bindings use this to construct
 * options from language-native types. Prefer `ConversionOptionsBuilder` for Rust code.
 */
data class ConversionOptionsUpdate(
    val headingStyle: HeadingStyle?,
    val listIndentType: ListIndentType?,
    val listIndentWidth: Long?,
    val bullets: String?,
    val strongEmSymbol: String?,
    val escapeAsterisks: Boolean?,
    val escapeUnderscores: Boolean?,
    val escapeMisc: Boolean?,
    val escapeAscii: Boolean?,
    val codeLanguage: String?,
    val autolinks: Boolean?,
    val defaultTitle: Boolean?,
    val brInTables: Boolean?,
    val highlightStyle: HighlightStyle?,
    val extractMetadata: Boolean?,
    val whitespaceMode: WhitespaceMode?,
    val stripNewlines: Boolean?,
    val wrap: Boolean?,
    val wrapWidth: Long?,
    val convertAsInline: Boolean?,
    val subSymbol: String?,
    val supSymbol: String?,
    val newlineStyle: NewlineStyle?,
    val codeBlockStyle: CodeBlockStyle?,
    val keepInlineImagesIn: List<String>?,
    val preprocessing: PreprocessingOptionsUpdate?,
    val encoding: String?,
    val debug: Boolean?,
    val stripTags: List<String>?,
    val preserveTags: List<String>?,
    val skipImages: Boolean?,
    val linkStyle: LinkStyle?,
    val outputFormat: OutputFormat?,
    val includeDocumentStructure: Boolean?,
    val extractImages: Boolean?,
    val maxImageSize: Long?,
    val captureSvg: Boolean?,
    val inferDimensions: Boolean?,
    val maxDepth: Long??,
    val excludeSelectors: List<String>?,
    val visitor: VisitorHandle?
)

/**
 * HTML preprocessing options for document cleanup before conversion.
 */
data class PreprocessingOptions(
    val enabled: Boolean,
    val preset: PreprocessingPreset,
    val removeNavigation: Boolean,
    val removeForms: Boolean
)

/**
 * Partial update for `PreprocessingOptions`.
 *
 * This struct uses `Option<T>` to represent optional fields that can be selectively updated.
 * Only specified fields (Some values) will override existing options; None values leave the
 * corresponding fields unchanged when applied via `PreprocessingOptions.apply_update`.
 */
data class PreprocessingOptionsUpdate(
    val enabled: Boolean?,
    val preset: PreprocessingPreset?,
    val removeNavigation: Boolean?,
    val removeForms: Boolean?
)

/**
 * A structured document tree representing the semantic content of an HTML document.
 *
 * Uses a flat node array with index-based parent/child references for efficient traversal.
 */
data class DocumentStructure(
    val nodes: List<DocumentNode>,
    val sourceFormat: String?
)

/**
 * A single node in the document tree.
 */
data class DocumentNode(
    val id: String,
    val content: NodeContent,
    val parent: Int?,
    val children: List<Int>,
    val annotations: List<TextAnnotation>,
    val attributes: Map<String, String>?
)

/**
 * An inline text annotation with byte-range offsets.
 *
 * Annotations describe formatting (bold, italic, etc.) and links within a node's text content.
 */
data class TextAnnotation(
    val start: Int,
    val end: Int,
    val kind: AnnotationKind
)

/**
 * The primary result of HTML conversion and extraction.
 *
 * Contains the converted text output, optional structured document tree,
 * metadata, extracted tables, images, and processing warnings.
 */
data class ConversionResult(
    val content: String?,
    val document: DocumentStructure?,
    val metadata: HtmlMetadata,
    val tables: List<TableData>,
    val images: List<String>,
    val warnings: List<ProcessingWarning>
)

/**
 * A structured table grid with cell-level data including spans.
 */
data class TableGrid(
    val rows: Int,
    val cols: Int,
    val cells: List<GridCell>
)

/**
 * A single cell in a table grid.
 */
data class GridCell(
    val content: String,
    val row: Int,
    val col: Int,
    val rowSpan: Int,
    val colSpan: Int,
    val isHeader: Boolean
)

/**
 * A top-level extracted table with both structured data and markdown representation.
 */
data class TableData(
    val grid: TableGrid,
    val markdown: String
)

/**
 * A non-fatal warning generated during HTML processing.
 */
data class ProcessingWarning(
    val message: String,
    val kind: WarningKind
)

/**
 * Type alias for a visitor handle (`Arc`-wrapped `Mutex` for thread-safe shared mutation).
 *
 * `Send + Sync` so that types embedding a `VisitorHandle` (e.g. `ConversionOptions`)
 * can be shared across threads — required by callers that stash configs inside
 * axum/rmcp/tokio Send-bound contexts.
 */
class VisitorHandle {}

/**
 * Visitor trait for HTML→Markdown conversion.
 *
 * Implement this trait to customize the conversion behavior for any HTML element type.
 * All methods have default implementations that return `VisitResult.Continue`, allowing
 * selective override of only the elements you care about.
 *
 * # Method Naming Convention
 *
 * - `visit_*_start`: Called before entering an element (pre-order traversal)
 * - `visit_*_end`: Called after exiting an element (post-order traversal)
 * - `visit_*`: Called for specific element types (e.g., `visit_link`, `visit_image`)
 *
 * # Execution Order
 *
 * For a typical element like `<div><p>text</p></div>`:
 * 1. `visit_element_start` for `<div>`
 * 2. `visit_element_start` for `<p>`
 * 3. `visit_text` for "text"
 * 4. `visit_element_end` for `<p>`
 * 5. `visit_element_end` for `</div>`
 *
 * # Performance Notes
 *
 * - `visit_text` is the most frequently called method (~100+ times per document)
 * - Return `VisitResult.Continue` quickly for elements you don't need to customize
 * - Avoid heavy computation in visitor methods; consider caching if needed
 */
class HtmlVisitor {}

/**
 * Context information passed to all visitor methods.
 *
 * Provides comprehensive metadata about the current node being visited,
 * including its type, attributes, position in the DOM tree, and parent context.
 */
data class NodeContext(
    val nodeType: NodeType,
    val tagName: String,
    val attributes: Map<String, String>,
    val depth: Long,
    val indexInParent: Long,
    val parentTag: String?,
    val isInline: Boolean
)

/**
 * Text directionality of document content.
 *
 * Corresponds to the HTML `dir` attribute and `bdi` element directionality.
 */
enum class TextDirection {
    LEFT_TO_RIGHT,
    RIGHT_TO_LEFT,
    AUTO;
}

/**
 * Link classification based on href value and document context.
 *
 * Used to categorize links during extraction for filtering and analysis.
 */
enum class LinkType {
    ANCHOR,
    INTERNAL,
    EXTERNAL,
    EMAIL,
    PHONE,
    OTHER;
}

/**
 * Image source classification for proper handling and processing.
 *
 * Determines whether an image is embedded (data URI), inline SVG, external, or relative.
 */
enum class ImageType {
    DATA_URI,
    INLINE_SVG,
    EXTERNAL,
    RELATIVE;
}

/**
 * Structured data format type.
 *
 * Identifies the schema/format used for structured data markup.
 */
enum class StructuredDataType {
    JSON_LD,
    MICRODATA,
    R_D_FA;
}

/**
 * HTML preprocessing aggressiveness level.
 *
 * Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
 */
enum class PreprocessingPreset {
    MINIMAL,
    STANDARD,
    AGGRESSIVE;
}

/**
 * Heading style options for Markdown output.
 *
 * Controls how headings (h1-h6) are rendered in the output Markdown.
 */
enum class HeadingStyle {
    UNDERLINED,
    ATX,
    ATX_CLOSED;
}

/**
 * List indentation character type.
 *
 * Controls whether list items are indented with spaces or tabs.
 */
enum class ListIndentType {
    SPACES,
    TABS;
}

/**
 * Whitespace handling strategy during conversion.
 *
 * Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
 */
enum class WhitespaceMode {
    NORMALIZED,
    STRICT;
}

/**
 * Line break syntax in Markdown output.
 *
 * Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
 */
enum class NewlineStyle {
    SPACES,
    BACKSLASH;
}

/**
 * Code block fence style in Markdown output.
 *
 * Determines how code blocks (`<pre><code>`) are rendered in Markdown.
 */
enum class CodeBlockStyle {
    INDENTED,
    BACKTICKS,
    TILDES;
}

/**
 * Highlight rendering style for `<mark>` elements.
 *
 * Controls how highlighted text is rendered in Markdown output.
 */
enum class HighlightStyle {
    DOUBLE_EQUAL,
    HTML,
    BOLD,
    NONE;
}

/**
 * Link rendering style in Markdown output.
 *
 * Controls whether links and images use inline `[text](url)` syntax or
 * reference-style `[text][1]` syntax with definitions collected at the end.
 */
enum class LinkStyle {
    INLINE,
    REFERENCE;
}

/**
 * Output format for conversion.
 *
 * Specifies the target markup language format for the conversion output.
 */
enum class OutputFormat {
    MARKDOWN,
    DJOT,
    PLAIN;
}

/**
 * The semantic content type of a document node.
 *
 * Uses internally tagged representation (`"node_type": "heading"`) for JSON serialization.
 */
sealed class NodeContent {
    data class Heading(
        val level: Byte,
        val text: String
    ) : NodeContent()
    data class Paragraph(
        val text: String
    ) : NodeContent()
    data class List(
        val ordered: Boolean
    ) : NodeContent()
    data class ListItem(
        val text: String
    ) : NodeContent()
    data class Table(
        val grid: TableGrid
    ) : NodeContent()
    data class Image(
        val description: String?,
        val src: String?,
        val imageIndex: Int?
    ) : NodeContent()
    data class Code(
        val text: String,
        val language: String?
    ) : NodeContent()
    object Quote : NodeContent()
    object DefinitionList : NodeContent()
    data class DefinitionItem(
        val term: String,
        val definition: String
    ) : NodeContent()
    data class RawBlock(
        val format: String,
        val content: String
    ) : NodeContent()
    data class MetadataBlock(
        val entries: List<String>
    ) : NodeContent()
    data class Group(
        val label: String?,
        val headingLevel: Byte?,
        val headingText: String?
    ) : NodeContent()
}

/**
 * The type of an inline text annotation.
 *
 * Uses internally tagged representation (`"annotation_type": "bold"`) for JSON serialization.
 */
sealed class AnnotationKind {
    object Bold : AnnotationKind()
    object Italic : AnnotationKind()
    object Underline : AnnotationKind()
    object Strikethrough : AnnotationKind()
    object Code : AnnotationKind()
    object Subscript : AnnotationKind()
    object Superscript : AnnotationKind()
    object Highlight : AnnotationKind()
    data class Link(
        val url: String,
        val title: String?
    ) : AnnotationKind()
}

/**
 * Categories of processing warnings.
 */
enum class WarningKind {
    IMAGE_EXTRACTION_FAILED,
    ENCODING_FALLBACK,
    TRUNCATED_INPUT,
    MALFORMED_HTML,
    SANITIZATION_APPLIED,
    DEPTH_LIMIT_EXCEEDED;
}

/**
 * Node type enumeration covering all HTML element types.
 *
 * This enum categorizes all HTML elements that the converter recognizes,
 * providing a coarse-grained classification for visitor dispatch.
 */
enum class NodeType {
    TEXT,
    ELEMENT,
    HEADING,
    PARAGRAPH,
    DIV,
    BLOCKQUOTE,
    PRE,
    HR,
    LIST,
    LIST_ITEM,
    DEFINITION_LIST,
    DEFINITION_TERM,
    DEFINITION_DESCRIPTION,
    TABLE,
    TABLE_ROW,
    TABLE_CELL,
    TABLE_HEADER,
    TABLE_BODY,
    TABLE_HEAD,
    TABLE_FOOT,
    LINK,
    IMAGE,
    STRONG,
    EM,
    CODE,
    STRIKETHROUGH,
    UNDERLINE,
    SUBSCRIPT,
    SUPERSCRIPT,
    MARK,
    SMALL,
    BR,
    SPAN,
    ARTICLE,
    SECTION,
    NAV,
    ASIDE,
    HEADER,
    FOOTER,
    MAIN,
    FIGURE,
    FIGCAPTION,
    TIME,
    DETAILS,
    SUMMARY,
    FORM,
    INPUT,
    SELECT,
    OPTION,
    BUTTON,
    TEXTAREA,
    LABEL,
    FIELDSET,
    LEGEND,
    AUDIO,
    VIDEO,
    PICTURE,
    SOURCE,
    IFRAME,
    SVG,
    CANVAS,
    RUBY,
    RT,
    RP,
    ABBR,
    KBD,
    SAMP,
    VAR,
    CITE,
    Q,
    DEL,
    INS,
    DATA,
    METER,
    PROGRESS,
    OUTPUT,
    TEMPLATE,
    SLOT,
    HTML,
    HEAD,
    BODY,
    TITLE,
    META,
    LINK_TAG,
    STYLE,
    SCRIPT,
    BASE,
    CUSTOM;
}

/**
 * Result of a visitor callback.
 *
 * Allows visitors to control the conversion flow by either proceeding
 * with default behavior, providing custom output, skipping elements,
 * preserving HTML, or signaling errors.
 */
sealed class VisitResult {
    object Continue : VisitResult()
    data class Custom(
        val field0: String
    ) : VisitResult()
    object Skip : VisitResult()
    object PreserveHtml : VisitResult()
    data class Error(
        val field0: String
    ) : VisitResult()
}

/**
 * Errors that can occur during HTML to Markdown conversion.
 */
sealed class ConversionError(message: String) : Exception(message) {
    data class ParseError(
        val field0: String
    ) : ConversionError("HTML parsing error: {0}")
    data class SanitizationError(
        val field0: String
    ) : ConversionError("Sanitization error: {0}")
    data class ConfigError(
        val field0: String
    ) : ConversionError("Invalid configuration: {0}")
    data class IoError(
        val field0: String
    ) : ConversionError("I/O error: {0}")
    data class Panic(
        val field0: String
    ) : ConversionError("Internal panic: {0}")
    data class InvalidInput(
        val field0: String
    ) : ConversionError("Invalid input: {0}")
    data class Other(
        val field0: String
    ) : ConversionError("Conversion error: {0}")
}

object HtmlToMarkdownRs {
    /**
     * Convert HTML to Markdown, returning a `ConversionResult` with content, metadata, images,
     * and warnings.
     *
     * **Errors:**
     *
     * Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
     */
    fun convert(html: String, options: ConversionOptions? = null): ConversionResult {

        return Bridge.convert(html, options)
    }

}
