// Generated by alef. Do not edit by hand.
// alef:hash:06a07f59ff322c5fa6ed3766823355b3456bd29753f0289e14bc8234d55bb3e7
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package dev.kreuzberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init {
        System.loadLibrary("htm_jni")
    }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI trait-bridge external funs — implementations are Rust JNI shims.

    // Destructor external funs for handle-only opaque types.
    external fun nativeFreeVisitorHandle(handle: Long)
}
