// Generated by alef. Do not edit by hand.
// alef:hash:a5b3f996ee92f829738c65f0dd7cd71017c0f67468cdb2976b3a3d616a35faee

package dev.kreuzberg.android

class HtmlToMarkdownRsBridgeException(message: String?, cause: Throwable?) :
    RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
