// Generated by alef. Do not edit by hand.
// alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package dev.kreuzberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init { System.loadLibrary("htm_jni") }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI trait-bridge external funs — implementations are Rust JNI shims.

    // Destructor external funs for handle-only opaque types.
    external fun nativeFreeVisitorHandle(handle: Long)
}
