// Generated by alef. Do not edit by hand.
// alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7

package dev.kreuzberg.android

class HtmlToMarkdownRsBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
