// Generated by alef. Do not edit by hand.
// alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.android

/** HTML preprocessing options for document cleanup before conversion. */
data class PreprocessingOptions(
    /** Enable HTML preprocessing globally */
    val enabled: Boolean = true,
    /** Preprocessing preset level (Minimal, Standard, Aggressive) */
    val preset: PreprocessingPreset = PreprocessingPreset.STANDARD,
    /** Remove navigation elements (nav, breadcrumbs, menus, sidebars) */
    val removeNavigation: Boolean = true,
    /** Remove form elements (forms, inputs, buttons, etc.) */
    val removeForms: Boolean = true,
)
