// Generated by alef. Do not edit by hand.
// alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg.android

/**
 * Partial update for `PreprocessingOptions`.
 *
 * This struct uses `Option<T>` to represent optional fields that can be selectively updated. Only
 * specified fields (Some values) will override existing options; None values leave the
 * corresponding fields unchanged when applied via `PreprocessingOptions.apply_update`.
 */
data class PreprocessingOptionsUpdate(
    /** Optional global preprocessing enablement override */
    val enabled: Boolean? = null,
    /** Optional preprocessing preset level override (Minimal, Standard, Aggressive) */
    val preset: PreprocessingPreset? = null,
    /** Optional navigation element removal override (nav, breadcrumbs, menus, sidebars) */
    val removeNavigation: Boolean? = null,
    /** Optional form element removal override (forms, inputs, buttons, etc.) */
    val removeForms: Boolean? = null,
)
