// Generated by alef. Do not edit by hand.
// alef:hash:343ebe0b8cb2b70f17247e419c6a21e0940eb11e4428ec2d98aa63d39bd5a9c3
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg.android

/**
 * HTML preprocessing aggressiveness level.
 *
 * Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
 */
enum class PreprocessingPreset {
    /** Minimal cleanup. Remove only essential noise (scripts, styles). */
    @com.fasterxml.jackson.annotation.JsonProperty("Minimal") MINIMAL,
    /** Standard cleanup. Default. Removes navigation, forms, and other auxiliary content. */
    @com.fasterxml.jackson.annotation.JsonProperty("Standard") STANDARD,
    /** Aggressive cleanup. Remove extensive non-content elements and structure. */
    @com.fasterxml.jackson.annotation.JsonProperty("Aggressive") AGGRESSIVE;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            MINIMAL -> "Minimal"
            STANDARD -> "Standard"
            AGGRESSIVE -> "Aggressive"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): PreprocessingPreset =
            when (value) {
                "Minimal",
                "minimal" -> MINIMAL
                "Standard",
                "standard" -> STANDARD
                "Aggressive",
                "aggressive" -> AGGRESSIVE
                else -> throw IllegalArgumentException("Unknown PreprocessingPreset value: $value")
            }
    }
}
