// Generated by alef. Do not edit by hand.
// alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg.android

/**
 * Whitespace handling strategy during conversion.
 *
 * Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
 */
enum class WhitespaceMode {
    /**
     * Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("Normalized") NORMALIZED,
    /** Preserve all whitespace exactly as it appears in the HTML. */
    @com.fasterxml.jackson.annotation.JsonProperty("Strict") STRICT;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
        when (this) {
            NORMALIZED -> "Normalized"
            STRICT -> "Strict"
        }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): WhitespaceMode =
            when (value) {
                "Normalized",
                "normalized" -> NORMALIZED
                "Strict",
                "strict" -> STRICT
                else -> throw IllegalArgumentException("Unknown WhitespaceMode value: $value")
            }
    }
}
