// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
