// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f18292b0d53a436265ef3bdcc55550a30dcac031a39b382a1546a698958ae266
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
