// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8fb4980b8f6485af19b29bb93f64385c7de27e575066bf6889391634150eaecf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
