// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea4caacfeb2ae44141b00dc26c07739a9ba3bf502166bab04463b4ec72405726
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import HtmlToMarkdownRs
import RustBridge

/// E2e tests for category: metadata.
final class MetadataTests: XCTestCase {
    func testMetadataAuthorMeta() throws {
        // Extract author from <meta name='author'> tag
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_author_meta)");
    }

    func testMetadataCanonicalUrl() throws {
        // Extract canonical URL from <link rel='canonical'> tag
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_canonical_url)");
    }

    func testMetadataDescriptionMeta() throws {
        // Extract description from <meta name='description'> tag
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_description_meta)");
    }

    func testMetadataDublinCore() throws {
        // Extract Dublin Core metadata tags
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_dublin_core)");
    }

    func testMetadataExtractAllImages() throws {
        // Extract all images from a document into metadata
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_extract_all_images)");
    }

    func testMetadataExtractAllLinks() throws {
        // Extract all links from a document into metadata
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_extract_all_links)");
    }

    func testMetadataHeadersHierarchy() throws {
        // Extract heading hierarchy from document into metadata
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_headers_hierarchy)");
    }

    func testMetadataKeywordsMeta() throws {
        // Extract keywords from <meta name='keywords'> tag
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_keywords_meta)");
    }

    func testMetadataLangAttribute() throws {
        // Extract language from html lang attribute
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_lang_attribute)");
    }

    func testMetadataMicrodataSchemaArticle() throws {
        // Extract schema.org microdata for Article
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_microdata_schema_article)");
    }

    func testMetadataMicrodataSchemaBreadcrumb() throws {
        // Extract schema.org breadcrumb navigation microdata
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_microdata_schema_breadcrumb)");
    }

    func testMetadataMicrodataSchemaOrganization() throws {
        // Extract schema.org microdata for Organization
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_microdata_schema_organization)");
    }

    func testMetadataMicrodataSchemaPerson() throws {
        // Extract schema.org microdata for Person
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_microdata_schema_person)");
    }

    func testMetadataMicrodataSchemaProduct() throws {
        // Extract schema.org microdata for Product
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_microdata_schema_product)");
    }

    func testMetadataTextDirectionLtr() throws {
        // Extract text direction from lang attribute on html element
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_text_direction_ltr)");
    }

    func testMetadataTextDirectionRtl() throws {
        // Extract right-to-left text direction
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_text_direction_rtl)");
    }

    func testMetadataTitleTag() throws {
        // Extract title from <title> tag
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: metadata_title_tag)");
    }

    func testOgBasicTags() throws {
        // Extract og:title, og:description, and og:image from Open Graph meta tags
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: og_basic_tags)");
    }

    func testOgMultipleTags() throws {
        // Extract multiple Open Graph tags including type, url, and site_name
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: og_multiple_tags)");
    }

    func testStructuredDataJsonLd() throws {
        // JSON-LD script tag is stripped from output (security) but metadata may be extracted
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: structured_data_json_ld)");
    }

    func testStructuredDataMultipleJsonLd() throws {
        // Multiple JSON-LD blocks are all stripped from output
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: structured_data_multiple_json_ld)");
    }

    func testTwitterCardTags() throws {
        // Extract Twitter card meta tags
        try XCTSkipIf(true, "swift: json_object request construction requires options_via configuration (fixture: twitter_card_tags)");
    }

}
