# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bbb3566c8608b55ca014e92563afb60b9662e8473a4975ee3146ff4ccac5605a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
