# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3288161abcd48034b98a56f9c383276302f3280f3991e1dce8793cf4a7891ca4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
