# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d54d668be048c4e75a97b3e3e35291bd9b0a7f9be8eb79a6a22f856594bc8bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
