// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a17843699ae58ecdab45276ab8539da058c5ef81065f3b146250c79aa0b8898
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
