// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df03cfa1ea58fc063ec7e305db2e9dcdc739bb4b063899fc4750f8584c5bd37e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
    private static final long serialVersionUID = 1L;
    /** The error code. */
    private final int code;

    /** Creates a new HtmlToMarkdownRsException. */
    public HtmlToMarkdownRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new HtmlToMarkdownRsException with a cause. */
    public HtmlToMarkdownRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
