// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:22cbc7728e7527feef8e06cb67ad8290c07e3c276a312d04d887bbecdf8f6101
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends HtmlToMarkdownRsException {
    private static final long serialVersionUID = 1L;

    /** Creates a new InvalidInputException. */
    public InvalidInputException(final String message) {
        super(1, message);
    }

    /** Creates a new InvalidInputException with a cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
