// DO NOT EDIT - auto-generated by alef
// alef:hash:526c92c34b7201230da79912b4ec8eb9ecc5c6683951a43cd0234a619377accd
package io.xberg.htmltomarkdown;

/**
 * I/O error — stores the error message string so the variant is FFI-safe.
 *
 * Use `ConversionError::from(io_error)` to convert from `std::io::Error`.
 */
public class IoErrorException extends ConversionErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new IoErrorException with the given message. */
    public IoErrorException(final String message) {
        super(message);
    }

    /** Creates a new IoErrorException with the given message and cause. */
    public IoErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
