// DO NOT EDIT - auto-generated by alef
// alef:hash:526c92c34b7201230da79912b4ec8eb9ecc5c6683951a43cd0234a619377accd
package io.xberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new PanicException with the given message. */
    public PanicException(final String message) {
        super(message);
    }

    /** Creates a new PanicException with the given message and cause. */
    public PanicException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
