// DO NOT EDIT - auto-generated by alef
// alef:hash:3b2349155f7fb028a2f1e87bb52f2e3008131ce2f4c23434c339d2d3b760adfe
package io.xberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new SanitizationErrorException with the given message. */
    public SanitizationErrorException(final String message) {
        super(message);
    }

    /** Creates a new SanitizationErrorException with the given message and cause. */
    public SanitizationErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
