// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b2349155f7fb028a2f1e87bb52f2e3008131ce2f4c23434c339d2d3b760adfe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Controls how the visitor affects the conversion pipeline. */
@SuppressWarnings("PMD")
public sealed interface VisitResult
permits VisitResult.Continue, VisitResult.Custom, VisitResult.Skip, VisitResult.PreserveHtml, VisitResult.Error {

    record Continue() implements VisitResult {}

    static VisitResult continue_() {
        return new Continue();
    }
    record Custom(String value) implements VisitResult {}

    static VisitResult custom(String value) {
        return new Custom(value);
    }
    record Skip() implements VisitResult {}

    static VisitResult skip() {
        return new Skip();
    }
    record PreserveHtml() implements VisitResult {}

    static VisitResult preserveHtml() {
        return new PreserveHtml();
    }
    record Error(String value) implements VisitResult {}

    static VisitResult error(String value) {
        return new Error(value);
    }
}
