# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e19f5e250479865621565e32ea53c3202125b83874ff092ae603c0e3a3069a19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: smoke

test_that("smoke_empty_string: Empty string produces empty output", {
  result <- convert(html = "", options = ConversionOptions$default())
  expect_equal(trimws(result$content), "")
})

test_that("smoke_simple_heading: H1 heading converts to ATX markdown", {
  result <- convert(html = "<h1>Title</h1>", options = ConversionOptions$default())
  expect_true(any(grepl("# Title", result$content, fixed = TRUE)))
})

test_that("smoke_simple_paragraph: Simple paragraph converts correctly", {
  result <- convert(html = "<p>Hello World</p>", options = ConversionOptions$default())
  expect_equal(trimws(result$content), "Hello World")
  expect_true(if (is.character(result$content)) length(result$content) > 0 && any(nchar(result$content) > 0) else length(result$content) > 0)
})
