// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:24c6ec3947de93edbf4fd9f6a3aa4efefc7c913bd25f7796723c95eb69dbe282
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const html_to_markdown = @import("html_to_markdown");

// E2e tests for category: visitor

test "visitor_audio_custom" {
    // Visitor replaces audio element with custom output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Listen to this: <audio src=\"podcast.mp3\" controls></audio></p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[AUDIO: podcast.mp3]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Listen to this:") != null);
    }
}

test "visitor_audio_skip" {
    // Visitor removes audio elements from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Background music:</p><audio src=\"music.ogg\" autoplay></audio><p>Enjoy!</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Background music:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Enjoy!") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "music.ogg") == null);
    }
}

test "visitor_button_custom" {
    // Visitor replaces button with bracketed text
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Confirm action: <button type=\"submit\">Click me</button> or <button type=\"reset\">Cancel</button></p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[BTN:Click me]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[BTN:Cancel]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Confirm action:") != null);
    }
}

test "visitor_button_skip" {
    // Visitor removes all buttons from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Actions available: <button>Save</button> <button>Delete</button> <button>Export</button></p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Actions available:") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Save") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Delete") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Export") == null);
    }
}

test "visitor_continue_default" {
    // Visitor continue action preserves default conversion
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Hello <strong>World</strong></p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "**World**") != null);
    }
}

test "visitor_custom_blockquote" {
    // Visitor replaces blockquote with custom format
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<blockquote><p>A wise quote.</p></blockquote>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "QUOTE:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "A wise quote.") != null);
    }
}

test "visitor_custom_emphasis" {
    // Visitor replaces emphasis with custom output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>This is <em>important</em> text.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, ">>>important<<<") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "*important*") == null);
    }
}

test "visitor_custom_heading" {
    // Visitor replaces heading with custom format
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h2>Section Title</h2><p>Content below heading.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "--- Section Title ---") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "## Section Title") == null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Content below heading.") != null);
    }
}

test "visitor_custom_image" {
    // Visitor replaces image with custom output using template
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<img src=\"banner.png\" alt=\"Banner\">", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[Image: Banner]") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "banner.png") == null);
    }
}

test "visitor_custom_link_format" {
    // Visitor reformats links using template interpolation
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Visit <a href=\"https://example.com\">Example</a> for more info.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Example (https://example.com)") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "[Example]") == null);
    }
}

test "visitor_custom_link_static" {
    // Visitor replaces link with static custom output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<a href=\"https://example.com\">Click here</a>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[REDACTED LINK]") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "example.com") == null);
    }
}

test "visitor_custom_output" {
    // Visitor custom action replaces element output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h1>Original Heading</h1>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "## REPLACED HEADING") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "# Original Heading") == null);
    }
}

test "visitor_definition_list_custom" {
    // Visitor customizes definition list items
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<dl><dt>HTML</dt><dd>HyperText Markup Language</dd><dt>CSS</dt><dd>Cascading Style Sheets</dd></dl>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "**HTML**") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "**CSS**") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "HyperText Markup Language") != null);
    }
}

test "visitor_definition_list_custom_format" {
    // Visitor formats definition lists with custom templates
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<dl><dt>Python</dt><dd>A high-level programming language</dd><dt>JavaScript</dt><dd>A scripting language for web browsers</dd></dl>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "### Python") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "### JavaScript") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "> A high-level programming language") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "> A scripting language for web browsers") != null);
    }
}

test "visitor_definition_list_skip" {
    // Visitor skips definition list items from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Glossary:</p><dl><dt>Term A</dt><dd>Definition of term A</dd><dt>Term B</dt><dd>Definition of term B</dd></dl><p>End of glossary</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Glossary:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "End of glossary") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Term A") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Definition") == null);
    }
}

test "visitor_details_summary_custom" {
    // Visitor customizes details/summary disclosure elements
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<details><summary>Click to expand</summary><p>This content is initially hidden.</p><p>But can be revealed by the user.</p></details>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[EXPANDABLE] Click to expand") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "This content is initially hidden.") != null);
    }
}

test "visitor_details_summary_skip" {
    // Visitor removes details/summary elements entirely
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Main content here.</p><details><summary>Hidden section</summary><p>Secret details</p></details><p>More main content.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Main content here.") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "More main content.") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Hidden section") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Secret details") == null);
    }
}

test "visitor_figure_custom" {
    // Visitor customizes figure and figcaption elements
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<article><h1>Article Title</h1><p>Introduction paragraph.</p><figure><img src=\"diagram.png\" alt=\"System architecture diagram\"><figcaption>Figure 1: System Architecture</figcaption></figure><p>Explanation of the figure.</p></article>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Article Title") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "*Figure 1: System Architecture*") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Explanation of the figure.") != null);
    }
}

test "visitor_figure_custom_wrap" {
    // Visitor wraps figure content with custom formatting
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<section><h2>Gallery</h2><figure><img src=\"photo1.jpg\" alt=\"Photo\"><figcaption>Beautiful sunset</figcaption></figure></section>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[FIGURE]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[/FIGURE]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Gallery") != null);
    }
}

test "visitor_figure_skip" {
    // Visitor removes figure elements with their captions
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>See the chart below:</p><figure><img src=\"chart.svg\"><figcaption>Revenue Trends 2020-2024</figcaption></figure><p>As shown in the chart above.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "See the chart below:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "As shown in the chart above.") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Revenue Trends") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "chart.svg") == null);
    }
}

test "visitor_form_custom" {
    // Visitor replaces form with custom output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<div><form action=\"/submit\" method=\"POST\"><label>Name: <input type=\"text\" name=\"name\"></label><button type=\"submit\">Submit</button></form></div>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[FORM PLACEHOLDER]") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "submit") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "input") == null);
    }
}

test "visitor_form_skip" {
    // Visitor skips form elements entirely
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Before form</p><form><input type=\"email\" name=\"email\"></form><p>After form</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Before form") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "After form") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "email") == null);
    }
}

test "visitor_heading_bare_string_preserves_case" {
    // Visitor returns rendered heading template as bare string; mixed-case is preserved (regression guard for issue #350)
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h2>Important Section Title</h2><p>Body.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "## Important Section Title ##") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "important section title") == null);
    }
}

test "visitor_horizontal_rule_custom" {
    // Visitor replaces horizontal rule with custom output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h1>Section A</h1><p>Content A</p><hr><h1>Section B</h1><p>Content B</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[DIVIDER]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Section A") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Section B") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "---") == null);
    }
}

test "visitor_horizontal_rule_skip" {
    // Visitor removes all horizontal rules
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Part 1</p><hr><p>Part 2</p><hr><p>Part 3</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Part 1") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Part 2") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Part 3") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "---") == null);
    }
}

test "visitor_iframe_custom" {
    // Visitor replaces embedded iframe with custom text
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Embedded map:</p><iframe src=\"https://maps.example.com/embed\" width=\"400\" height=\"300\"></iframe><p>End of map</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[EMBEDDED: https://maps.example.com/embed]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Embedded map:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "End of map") != null);
    }
}

test "visitor_iframe_skip" {
    // Visitor removes embedded iframes
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h3>Reviews</h3><iframe src=\"https://widget.example.com/reviews\"></iframe><p>See reviews from our partners.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Reviews") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "See reviews from our partners.") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "widget.example.com") == null);
    }
}

test "visitor_image_bare_string_preserves_case" {
    // Visitor returns bare-string image replacement; mixed-case alt/src preserved (regression guard for issue #350)
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<img src=\"PhotoOne.JPG\" alt=\"Sunset Over Bay\">", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[image: Sunset Over Bay -> PhotoOne.JPG]") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "sunset over bay") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "photoone.jpg") == null);
    }
}

test "visitor_input_custom" {
    // Visitor replaces input with labeled output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<form><label>Username: <input type=\"text\" name=\"username\" value=\"\"></label><label>Password: <input type=\"password\" name=\"password\"></label></form>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[INPUT:text]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[INPUT:password]") != null);
    }
}

test "visitor_input_skip" {
    // Visitor skips all input elements
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Sign up:</p><input type=\"text\" name=\"email\" placeholder=\"your@email.com\"><input type=\"checkbox\" name=\"agree\"><p>Continue</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Sign up:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Continue") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "email") == null);
    }
}

test "visitor_line_break_custom" {
    // Visitor replaces line break with custom output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>First line<br>Second line<br>Third line</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "First line | Second line | Third line") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "\n\n") == null);
    }
}

test "visitor_line_break_skip" {
    // Visitor removes all line breaks
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Address Line 1<br>Address Line 2<br>Address Line 3</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Address Line 1Address Line 2Address Line 3") != null);
    }
}

test "visitor_link_bare_string_preserves_case" {
    // Visitor returns rendered template as a bare string (not a dict) and original mixed-case content is preserved end-to-end (regression guard for issue #350)
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<a href=\"https://old-cdn.com/file.pdf\">Download</a>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[Download](https://new-cdn.com/file.pdf)") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "[download]") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "old-cdn.com") == null);
    }
}

test "visitor_mark_custom" {
    // Visitor replaces highlight/mark with custom template
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>This is a <mark>highlighted passage</mark> in the text.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "==highlighted passage==") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "This is a") != null);
    }
}

test "visitor_mark_skip" {
    // Visitor skips mark elements entirely
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Key insight: <mark>always validate input</mark> for security.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "always validate input") == null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Key insight:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "for security.") != null);
    }
}

test "visitor_preserve_html" {
    // Visitor preserve_html action includes raw HTML in output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<div><custom-tag>Custom content</custom-tag></div>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "<custom-tag>") != null);
    }
}

test "visitor_skip_code_blocks" {
    // Visitor skips code blocks from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Intro text</p><pre><code>let x = 42;</code></pre><p>Outro text</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Intro text") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Outro text") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "let x = 42") == null);
    }
}

test "visitor_skip_heading" {
    // Visitor skip action omits all headings from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h1>Title</h1><p>Body text remains.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "Title") == null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Body text remains.") != null);
    }
}

test "visitor_skip_images" {
    // Visitor skips all images from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Before image</p><img src=\"photo.jpg\" alt=\"A photo\"><p>After image</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Before image") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "After image") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "photo.jpg") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "A photo") == null);
    }
}

test "visitor_skip_links" {
    // Visitor skips all links entirely
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Before <a href=\"https://example.com\">link text</a> after</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "link text") == null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "example.com") == null);
    }
}

test "visitor_skip_strong" {
    // Visitor skips bold/strong elements
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Normal <strong>bold text</strong> normal</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "bold text") == null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Normal") != null);
    }
}

test "visitor_subscript_custom" {
    // Visitor replaces subscript with custom template
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>H<sub>2</sub>O is water.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "H~2~O") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "is water") != null);
    }
}

test "visitor_subscript_skip" {
    // Visitor skips subscript elements entirely
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>The formula C<sub>12</sub>H<sub>22</sub>O<sub>11</sub> is sugar.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "The formula CHO is sugar.") != null);
    }
}

test "visitor_superscript_custom" {
    // Visitor replaces superscript with custom template
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Einstein's E=mc<sup>2</sup> revolutionized physics.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "E=mc^2^") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "revolutionized physics") != null);
    }
}

test "visitor_superscript_skip" {
    // Visitor skips superscript from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>The equation x<sup>3</sup> + y<sup>3</sup> = z<sup>3</sup> has no solutions.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "The equation x + y = z has no solutions.") != null);
    }
}

test "visitor_underline_custom" {
    // Visitor replaces underline with custom markup
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>This is <u>very important</u> text.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "_very important_") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "**") == null);
    }
}

test "visitor_underline_skip" {
    // Visitor skips underline elements from output
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Normal text with <u>underlined part</u> and more text.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Normal text with") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "and more text.") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "underlined part") == null);
    }
}

test "visitor_video_custom" {
    // Visitor replaces video with custom link
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<p>Watch our tutorial:</p><video src=\"tutorial.mp4\" width=\"320\" height=\"240\" controls></video><p>Great content!</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "[VIDEO: tutorial.mp4]") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Watch our tutorial:") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Great content!") != null);
    }
}

test "visitor_video_skip" {
    // Visitor removes video elements entirely
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try html_to_markdown.convert("<h2>Demo</h2><video src=\"demo.webm\"></video><p>See the demo above.</p>", null);
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "Demo") != null);
    }
    {
        const _jv = result.object.get("content").?;
        const _js = if (_jv == .string) _jv.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jv, .{});
        defer if (_jv != .string) std.heap.c_allocator.free(_js);
        try testing.expect(std.mem.indexOf(u8, _js, "See the demo above.") != null);
    }
    {
        const _jvnc = result.object.get("content").?;
        const _jsnc = if (_jvnc == .string) _jvnc.string else try std.json.Stringify.valueAlloc(std.heap.c_allocator, _jvnc, .{});
        defer if (_jvnc != .string) std.heap.c_allocator.free(_jsnc);
        try testing.expect(std.mem.indexOf(u8, _jsnc, "demo.webm") == null);
    }
}
