// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0bb33f61f6b0fb21b11f0a4a6816b4de0f2a0ab1fc607ebf1ecf2f5cacf7ffea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import HtmlToMarkdown
import RustBridge

/// E2e tests for category: smoke.
final class SmokeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testSmokeEmptyString() throws {
        // Empty string produces empty output
        let _options = try HtmlToMarkdown.conversionOptionsFromJson("{}")
        let result = try HtmlToMarkdown.convert(html: "", options: _options)
        XCTAssertEqual((result.content()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "")
    }

    func testSmokeSimpleHeading() throws {
        // H1 heading converts to ATX markdown
        let _options = try HtmlToMarkdown.conversionOptionsFromJson("{}")
        let result = try HtmlToMarkdown.convert(html: "<h1>Title</h1>", options: _options)
        XCTAssertTrue((result.content()?.toString() ?? "").contains("# Title"), "expected to contain: \("# Title")")
    }

    func testSmokeSimpleParagraph() throws {
        // Simple paragraph converts correctly
        let _options = try HtmlToMarkdown.conversionOptionsFromJson("{}")
        let result = try HtmlToMarkdown.convert(html: "<p>Hello World</p>", options: _options)
        XCTAssertEqual((result.content()?.toString() ?? "").trimmingCharacters(in: CharacterSet.whitespacesAndNewlines), "Hello World")
        XCTAssertNotNil(result.content(), "expected non-nil value")
    }

}
