<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9664cce23f34ebb1892e8ff0cf055a84db187fc3e7376d4266d540b27487ddd7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
declare(strict_types=1);

namespace HtmlToMarkdown;

final class HtmlToMarkdown
{
    /**
     * Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images,
     * and warnings.
     *
     * @param string $html
     * @param ?ConversionOptions $options
     * @return ConversionResult
     * @throws \HtmlToMarkdown\HtmlToMarkdownException
     */
    public static function convert(
        string $html,
        ?ConversionOptions $options = null,
    ): ConversionResult {
        return \HtmlToMarkdown\HtmlToMarkdownApi::convert($html, $options); // delegate to native extension class
    }
}
