<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d20647b3bbb73aa6fb1e683b49b0ca13d93d44d42995a47162bff61fb9b76b78
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace HtmlToMarkdown;

final class HtmlToMarkdown
{
    /**
     * Convert HTML to Markdown, Djot, or plain text.
     *
     * Returns a [`ConversionResult`] with converted content plus optional metadata,
     * document structure, table data, inline images, and warnings depending on the
     * enabled features and conversion options.
     *
     * @param string $html
     * @param ?ConversionOptions $options
     * @return ConversionResult
     * @throws \HtmlToMarkdown\HtmlToMarkdownException
     */
    public static function convert(string $html, ?ConversionOptions $options = null): ConversionResult
    {
        return \HtmlToMarkdown\HtmlToMarkdownApi::convert($html, $options); // delegate to native extension class
    }
}
