<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f35332d4a7ca61d2e6967470e17646d8c71fd62e56a119dedc9617e1fa63817
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace HtmlToMarkdown;
/**
 * Type alias for a visitor handle (`Arc`-wrapped `Mutex` for thread-safe shared mutation).
 *
 * `Send + Sync` so that types embedding a `VisitorHandle` (e.g. `ConversionOptions`)
 * can be shared across threads — required by callers that stash configs inside
 * axum/rmcp/tokio Send-bound contexts.
 */
final class VisitorHandle
{
}
