// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.htmltomarkdown.HtmlToMarkdownRs;
import dev.kreuzberg.htmltomarkdown.ConversionOptions;
import java.util.Optional;
import dev.kreuzberg.htmltomarkdown.JsonUtil;

/** E2e tests for category: smoke. */
public class SmokeTest {

    @Test
    void testSmokeEmptyString() throws Exception {
        // Empty string produces empty output
        var result = HtmlToMarkdownRs.convert("", ConversionOptions.builder().build());
assertEquals("", java.util.Optional.ofNullable(result.content()).map(java.util.Objects::toString).orElse("").trim());

    }


    @Test
    void testSmokeSimpleHeading() throws Exception {
        // H1 heading converts to ATX markdown
        var result = HtmlToMarkdownRs.convert("<h1>Title</h1>", ConversionOptions.builder().build());
assertTrue(java.util.Optional.ofNullable(result.content()).map(java.util.Objects::toString).orElse("").contains("# Title"), "expected to contain: " + "# Title");

    }


    @Test
    void testSmokeSimpleParagraph() throws Exception {
        // Simple paragraph converts correctly
        var result = HtmlToMarkdownRs.convert("<p>Hello World</p>", ConversionOptions.builder().build());
assertEquals("Hello World", java.util.Optional.ofNullable(result.content()).map(java.util.Objects::toString).orElse("").trim());assertFalse(java.util.Optional.ofNullable(result.content()).isEmpty(), "expected non-empty value");

    }

}
