# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c3ad5a882b36385eb49552278543097810607c89b84ce4b299ec2b918abc0d9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
