# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68ed85485c3c853b18048abf1b4810a85ae7e544606d018e0983d9d3fd88bee8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
