/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
#include <html_to_markdown.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  const char *version = htm_version();

  if (!version || strlen(version) == 0) {
    fprintf(stderr, "FAIL: expected non-empty version string\n");
    return 1;
  }

  printf("PASS: htm_version returned: %s\n", version);
  return 0;
}
