/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:b66e63bedbe733cdfecdde47f2dd4d3e56c53a31eafbcf1e90f990a2eeeed9ab
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
#include <html_to_markdown.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  const char *version = htm_version();

  if (!version || strlen(version) == 0) {
    fprintf(stderr, "FAIL: expected non-empty version string\n");
    return 1;
  }

  printf("PASS: htm_version returned: %s\n", version);
  return 0;
}
