/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:a7f7315ae9786ca9e8f870af4f75d4f4f80b350b3cdf1078712b8959443eaccd
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
#include <html_to_markdown.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  HtmResult result = htm_version();

  if (result.error_code != 0) {
    fprintf(stderr, "FAIL: htm_version returned error %d: %s\n",
            result.error_code, result.error_message ? result.error_message : "");
    htm_result_free(result);
    return 1;
  }

  if (!result.content || strlen(result.content) == 0) {
    fprintf(stderr, "FAIL: expected non-empty version string\n");
    htm_result_free(result);
    return 1;
  }

  printf("PASS: htm_version returned: %s\n", result.content);
  htm_result_free(result);
  return 0;
}
