# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b2349155f7fb028a2f1e87bb52f2e3008131ce2f4c23434c339d2d3b760adfe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
