# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3018ac86397d06eb06f0310e148b8377f08cc898c914c7151583d4603b1670d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
