# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d20647b3bbb73aa6fb1e683b49b0ca13d93d44d42995a47162bff61fb9b76b78
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
