# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "html_to_markdown/version"
require_relative "html_to_markdown/native"

# Top-level namespace for the HtmlToMarkdown Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "html_to_markdown/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module HtmlToMarkdown
  # Re-export all types and functions from native extension
end
