# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:120f46e2343431361d3a6c804f433935878e00960d289cb9d00d4ae834e8e6a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "html_to_markdown/version"
require_relative "html_to_markdown/native"

# Top-level namespace for the HtmlToMarkdown Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "html_to_markdown/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module HtmlToMarkdown
  # Re-export all types and functions from native extension
end
