# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2afc2d84509a11e0aa87ea3716174da373e726a4c032dea84b3ff6fb03374b26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'html_to_markdown/version'
require_relative 'html_to_markdown/native'

module HtmlToMarkdown
  # Re-export all types and functions from native extension
end
