# Generated by alef. Do not edit by hand.
# alef:hash:3288161abcd48034b98a56f9c383276302f3280f3991e1dce8793cf4a7891ca4
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.android.** { *; }
