# Generated by alef. Do not edit by hand.
# alef:hash:cd2834af6faec95ba72da53570d99ea0eac38dbafd9303b8cc9c178fc3d201ae
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.android.** { *; }
