# Generated by alef. Do not edit by hand.
# alef:hash:1da055e3cc170122f9709ca046a003279fd9b4ac758533f00d080b7fb9ebc446
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.android.** { *; }
