// Generated by alef. Do not edit by hand.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-android"
