# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b02c788745b375401daf19102376d59d2057f4ad3b5399fd76bd12fad0005c44
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.CodeBlockStyle do
  @moduledoc """
  Code block fence style in Markdown output.

  Determines how code blocks (`<pre><code>`) are rendered in Markdown.
  """

  @typedoc "Code block fence style in Markdown output."
  @type t :: :indented | :backticks | :tildes

  @indented :indented
  @backticks :backticks
  @tildes :tildes

  @doc "Indented code blocks (4 spaces). `CommonMark` standard."
  @spec indented() :: t()
  def indented, do: @indented
  @doc "Fenced code blocks with backticks (```). Default (GFM). Supports language hints."
  @spec backticks() :: t()
  def backticks, do: @backticks
  @doc "Fenced code blocks with tildes (~~~). Supports language hints."
  @spec tildes() :: t()
  def tildes, do: @tildes
end
