# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d20647b3bbb73aa6fb1e683b49b0ca13d93d44d42995a47162bff61fb9b76b78
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.CodeBlockStyle do
  @moduledoc """
  Code block fence style in Markdown output.

  Determines how code blocks (`<pre><code>`) are rendered in Markdown.
  """

  @typedoc "Code block fence style in Markdown output."
  @type t :: :indented | :backticks | :tildes

  @indented :indented
  @backticks :backticks
  @tildes :tildes

  @doc "Indented code blocks (4 spaces). `CommonMark` standard."
  @spec indented() :: t()
  def indented, do: @indented
  @doc "Fenced code blocks with triple backticks. Default (GFM). Supports language hints."
  @spec backticks() :: t()
  def backticks, do: @backticks
  @doc "Fenced code blocks with tildes (~~~). Supports language hints."
  @spec tildes() :: t()
  def tildes, do: @tildes
end
