# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44e2d75463a5dd5fcd6e1eb8848373eac19faf9c1aefbe14a0d4b612acdb99d7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc """
  A structured document tree representing the semantic content of an HTML document.

  Uses a flat node array with index-based parent/child references for efficient traversal.
  """

  @typedoc "A structured document tree representing the semantic content of an HTML document."
  @type t :: %__MODULE__{
          nodes: [map()],
          source_format: String.t() | nil
        }

  defstruct nodes: [],
            source_format: nil
end
