# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: String.t() | nil,
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          annotations: [map()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
