# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ba300ecbb725eb266bbcd4f47e9bc50e560372ba8b6f9d9f93c785e8758cdc8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: String.t() | nil,
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          annotations: [map()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
