# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe2faafad5d9f264f214640a6abbd281095c5e3558b650131b1ebee9748d9bc5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: String.t() | nil,
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          annotations: [HtmlToMarkdown.TextAnnotation.t()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
