# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7f7315ae9786ca9e8f870af4f75d4f4f80b350b3cdf1078712b8959443eaccd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc """
  A structured document tree representing the semantic content of an HTML document.

  Uses a flat node array with index-based parent/child references for efficient traversal.
  """

  @typedoc "A structured document tree representing the semantic content of an HTML document."
  @type t :: %__MODULE__{
          nodes: [map()],
          source_format: String.t() | nil
        }

  defstruct nodes: [],
            source_format: nil
end
