# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c6207c3ca07f462c7153c354b98cb895061fc623e2655bf7b92ce8738b5d167
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  @typedoc "A single cell in a table grid."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row: non_neg_integer(),
          col: non_neg_integer(),
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean()
        }

  defstruct content: nil,
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false
end
