# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22cbc7728e7527feef8e06cb67ad8290c07e3c276a312d04d887bbecdf8f6101
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.HeadingStyle do
  @moduledoc """
  Heading style options for Markdown output.

  Controls how headings (h1-h6) are rendered in the output Markdown.
  """

  @typedoc "Heading style options for Markdown output."
  @type t :: :underlined | :atx | :atx_closed

  @underlined :underlined
  @atx :atx
  @atx_closed :atx_closed

  @doc "Underlined style (=== for h1, --- for h2)."
  @spec underlined() :: t()
  def underlined, do: @underlined
  @doc "ATX style (# for h1, ## for h2, etc.). Default."
  @spec atx() :: t()
  def atx, do: @atx
  @doc "ATX closed style (# title #, with closing hashes)."
  @spec atx_closed() :: t()
  def atx_closed, do: @atx_closed
end
