# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd2834af6faec95ba72da53570d99ea0eac38dbafd9303b8cc9c178fc3d201ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.HtmlMetadata do
  @moduledoc """
  Comprehensive metadata extraction result from HTML document.

  Contains all extracted metadata types in a single structure,
  suitable for serialization and transmission across language boundaries.

  # Examples

  ```
  let metadata = HtmlMetadata {
      document: Default::default(),
      headers: Vec::new(),
      links: Vec::new(),
      images: Vec::new(),
      structured_data: Vec::new(),
  };

  assert!(metadata.headers.is_empty());
  ```
  """

  @typedoc "Comprehensive metadata extraction result from HTML document."
  @type t :: %__MODULE__{
          document: map(),
          headers: [map()],
          links: [map()],
          images: [map()],
          structured_data: [map()]
        }

  defstruct document: nil,
            headers: [],
            links: [],
            images: [],
            structured_data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
