# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:534d85f18def3251bfbbb2ed85d8b09f6193246b1fd67009783663871369f196
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.HtmlMetadata do
  @moduledoc "Comprehensive metadata extraction result from HTML document."

  defstruct document: nil,
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
