# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a38596f4710bb39705e17a2aa53410d79f7ecff7a95a76d54163138ea84aa29b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ImageMetadata do
  @moduledoc "Image metadata with source and dimensions."

  @type t :: %__MODULE__{
    src: String.t() | nil,
    alt: String.t() | nil,
    title: String.t() | nil,
    dimensions: [non_neg_integer()] | nil,
    image_type: String.t() | nil,
    attributes: map()
  }

  defstruct src: nil,
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: %{}
end
