# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f18292b0d53a436265ef3bdcc55550a30dcac031a39b382a1546a698958ae266
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule HtmlToMarkdown.LinkStyle do
  @moduledoc """
  Link rendering style in Markdown output.

  Controls whether links and images use inline `[text](url)` syntax or
  reference-style `[text][1]` syntax with definitions collected at the end.
  """

  @typedoc "Link rendering style in Markdown output."
  @type t :: :inline | :reference

  @inline :inline
  @reference :reference

  @doc "Inline links: `[text](url)`. Default."
  @spec inline() :: t()
  def inline, do: @inline
  @doc "Reference-style links: `[text][1]` with `[1]: url` at end of document."
  @spec reference() :: t()
  def reference, do: @reference
end
