# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.LinkMetadata do
  @moduledoc """
  Hyperlink metadata with categorization and attributes.

  Represents `<a>` elements with parsed href values, text content, and link type classification.

  # Examples

  ```
  let link = LinkMetadata {
      href: "https://example.com".to_string(),
      text: "Example".to_string(),
      title: Some("Visit Example".to_string()),
      link_type: LinkType::External,
      rel: vec!["nofollow".to_string()],
      attributes: Default::default(),
  };

  assert_eq!(link.link_type, LinkType::External);
  assert_eq!(link.text, "Example");
  ```
  """

  @typedoc "Hyperlink metadata with categorization and attributes."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: String.t() | nil,
          rel: [String.t()],
          attributes: map()
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: %{}
end
