# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:19bb30b9ab9930af82136c553420f84eaac0b1ace4e004f52b1309833ff65529
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.LinkType do
  @moduledoc """
  Link classification based on href value and document context.

  Used to categorize links during extraction for filtering and analysis.
  """

  @typedoc "Link classification based on href value and document context."
  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @doc "Anchor link within same document (href starts with #)"
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "Internal link within same domain"
  @spec internal() :: t()
  def internal, do: @internal
  @doc "External link to different domain"
  @spec external() :: t()
  def external, do: @external
  @doc "Email link (mailto:)"
  @spec email() :: t()
  def email, do: @email
  @doc "Phone link (tel:)"
  @spec phone() :: t()
  def phone, do: @phone
  @doc "Other protocol or unclassifiable"
  @spec other() :: t()
  def other, do: @other
end
