# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:77a993efaaebae8c3b23a2710d132d1b20b8c70281508df55aa4b842c9bca596
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.LinkStyle do
  @moduledoc """
  Link rendering style in Markdown output.

  Controls whether links and images use inline `[text](url)` syntax or
  reference-style `[text][1]` syntax with definitions collected at the end.
  """

  @typedoc "Link rendering style in Markdown output."
  @type t :: :inline | :reference

  @inline :inline
  @reference :reference

  @doc "Inline links: `[text](url)`. Default."
  @spec inline() :: t()
  def inline, do: @inline
  @doc "Reference-style links: `[text][1]` with `[1]: url` at end of document."
  @spec reference() :: t()
  def reference, do: @reference
end
