# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1da055e3cc170122f9709ca046a003279fd9b4ac758533f00d080b7fb9ebc446
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ListIndentType do
  @moduledoc """
  List indentation character type.

  Controls whether list items are indented with spaces or tabs.
  """

  @typedoc "List indentation character type."
  @type t :: :spaces | :tabs

  @spaces :spaces
  @tabs :tabs

  @doc "Use spaces for indentation. Default. Width controlled by `list_indent_width`."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Use tabs for indentation."
  @spec tabs() :: t()
  def tabs, do: @tabs
end
