# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.MetadataEntry do
  @moduledoc """
  A single key-value metadata entry from `<head>` meta tags.

  Binding-safe replacement for `(String, String)` tuples used in
  [`NodeContent::MetadataBlock`]. Tuple pairs cannot be represented
  across language boundaries without lossy degradation.
  """

  @typedoc "A single key-value metadata entry from `<head>` meta tags."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil
end
