# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:120f46e2343431361d3a6c804f433935878e00960d289cb9d00d4ae834e8e6a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.MetadataEntry do
  @moduledoc """
  A single key-value metadata entry from `<head>` meta tags.

  Binding-safe replacement for `(String, String)` tuples used in
  [`NodeContent::MetadataBlock`]. Tuple pairs cannot be represented
  across language boundaries without lossy degradation.
  """

  @typedoc "A single key-value metadata entry from `<head>` meta tags."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil
end
