# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc43c0c526ce156f6a575287c9df6d72d0edf70d00f6af31bcaee8ca0bbfe3eb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.MetadataEntry do
  @moduledoc """
  A single key-value metadata entry from `<head>` meta tags.

  Binding-safe replacement for `(String, String)` tuples used in
  [`NodeContent::MetadataBlock`]. Tuple pairs cannot be represented
  across language boundaries without lossy degradation.
  """

  @typedoc "A single key-value metadata entry from `<head>` meta tags."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil
end
