# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c6207c3ca07f462c7153c354b98cb895061fc623e2655bf7b92ce8738b5d167
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc """
  Line break syntax in Markdown output.

  Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
  """

  @typedoc "Line break syntax in Markdown output."
  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @doc "Two trailing spaces at end of line. Default. Standard Markdown syntax."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Backslash at end of line. Alternative Markdown syntax."
  @spec backslash() :: t()
  def backslash, do: @backslash
end
