# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da9cb387130ef3f6f1b6140ae9b4d20e65450a8936cc10ab9f8d5acb080fdbf5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.NodeContent do
  @moduledoc "The semantic content type of a document node."

  @type t :: term()

  @type heading :: %{type: :heading, level: non_neg_integer(), text: String.t()}
  @type paragraph :: %{type: :paragraph, text: String.t()}
  @type list_variant :: %{type: :list, ordered: boolean()}
  @type list_item :: %{type: :list_item, text: String.t()}
  @type table :: %{type: :table, grid: HtmlToMarkdown.TableGrid.t()}
  @type image :: %{type: :image, description: String.t(), src: String.t(), image_index: non_neg_integer()}
  @type code :: %{type: :code, text: String.t(), language: String.t()}
  @type quote :: :quote
  @type definition_list :: :definition_list
  @type definition_item :: %{type: :definition_item, term: String.t(), definition: String.t()}
  @type raw_block :: %{type: :raw_block, format: String.t(), content: String.t()}
  @type metadata_block :: %{type: :metadata_block, entries: [String.t()]}
  @type group :: %{type: :group, label: String.t(), heading_level: non_neg_integer(), heading_text: String.t()}
end
