# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd2834af6faec95ba72da53570d99ea0eac38dbafd9303b8cc9c178fc3d201ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc """
  Output format for conversion.

  Specifies the target markup language format for the conversion output.
  """

  @typedoc "Output format for conversion."
  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @doc "Standard Markdown (`CommonMark` compatible). Default."
  @spec markdown() :: t()
  def markdown, do: @markdown
  @doc "Djot lightweight markup language."
  @spec djot() :: t()
  def djot, do: @djot
  @doc "Plain text output (no markup, visible text only)."
  @spec plain() :: t()
  def plain, do: @plain
end
