# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc """
  Output format for conversion.

  Specifies the target markup language format for the conversion output.
  """

  @typedoc "Output format for conversion."
  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @doc "Standard Markdown (`CommonMark` compatible). Default."
  @spec markdown() :: t()
  def markdown, do: @markdown
  @doc "Djot lightweight markup language."
  @spec djot() :: t()
  def djot, do: @djot
  @doc "Plain text output (no markup, visible text only)."
  @spec plain() :: t()
  def plain, do: @plain
end
