# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e67924a4e20ae3baa3063a960ef4248e2ea060e7985280e4f28255482661bdd8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc """
  Output format for conversion.

  Specifies the target markup language format for the conversion output.
  """

  @typedoc "Output format for conversion."
  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @doc "Standard Markdown (CommonMark compatible). Default."
  @spec markdown() :: t()
  def markdown, do: @markdown
  @doc "Djot lightweight markup language."
  @spec djot() :: t()
  def djot, do: @djot
  @doc "Plain text output (no markup, visible text only)."
  @spec plain() :: t()
  def plain, do: @plain
end
