# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88c64fdb9c155eb72727cd57dc233c49e2c869ff15b9ffa53e1fd040bd6ff369
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.PreprocessingOptions do
  @moduledoc "HTML preprocessing options for document cleanup before conversion."

  @typedoc "HTML preprocessing options for document cleanup before conversion."
  @type t :: %__MODULE__{
          enabled: boolean(),
          preset: String.t() | nil,
          remove_navigation: boolean(),
          remove_forms: boolean()
        }

  defstruct enabled: true,
            preset: :standard,
            remove_navigation: true,
            remove_forms: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
