# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3478a445458a33d08bd86006e3bd2435c28bc2078c46d33f758971cc085f89ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc """
  HTML preprocessing aggressiveness level.

  Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
  """

  @typedoc "HTML preprocessing aggressiveness level."
  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @doc "Minimal cleanup. Remove only essential noise (scripts, styles)."
  @spec minimal() :: t()
  def minimal, do: @minimal
  @doc "Standard cleanup. Default. Removes navigation, forms, and other auxiliary content."
  @spec standard() :: t()
  def standard, do: @standard
  @doc "Aggressive cleanup. Remove extensive non-content elements and structure."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
