# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9d3514f25ebc55cbe6ad0e5642bde3bb7bc54ae2b61677afaddaeace6a9e2ee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc "Partial update for `PreprocessingOptions`."

  @type t :: %__MODULE__{
    enabled: boolean() | nil,
    preset: String.t() | nil | nil,
    remove_navigation: boolean() | nil,
    remove_forms: boolean() | nil
  }

  defstruct enabled: nil,
            preset: nil,
            remove_navigation: nil,
            remove_forms: nil
end
