# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:120f46e2343431361d3a6c804f433935878e00960d289cb9d00d4ae834e8e6a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc """
  Partial update for `PreprocessingOptions`.

  This struct uses `Option<T>` to represent optional fields that can be selectively updated.
  Only specified fields (Some values) will override existing options; None values leave the
  corresponding fields unchanged when applied via [`PreprocessingOptions::apply_update`].
  """

  @typedoc "Partial update for `PreprocessingOptions`."
  @type t :: %__MODULE__{
          enabled: boolean() | nil,
          preset: String.t() | nil | nil,
          remove_navigation: boolean() | nil,
          remove_forms: boolean() | nil
        }

  defstruct enabled: nil,
            preset: nil,
            remove_navigation: nil,
            remove_forms: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
