# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc """
  HTML preprocessing aggressiveness level.

  Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
  """

  @typedoc "HTML preprocessing aggressiveness level."
  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @doc "Minimal cleanup. Remove only essential noise (scripts, styles)."
  @spec minimal() :: t()
  def minimal, do: @minimal
  @doc "Standard cleanup. Default. Removes navigation, forms, and other auxiliary content."
  @spec standard() :: t()
  def standard, do: @standard
  @doc "Aggressive cleanup. Remove extensive non-content elements and structure."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
end
