# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9d42c169ca60d162717bbf9d0bf1242118764a41252df2dabe5b2393bb5a023a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc """
  A non-fatal diagnostic produced during HTML conversion.

  Warnings indicate that conversion completed but some content may have been handled
  differently than expected — for example, an image that could not be extracted, a truncated
  input, or malformed HTML that was repaired with best-effort parsing.

  Conversion always succeeds (returns `ConversionResult`) even when warnings are
  present. Callers should inspect `warnings` and decide how to
  handle them based on their tolerance for partial results:

  - **Logging pipelines**: emit each warning at `WARN` level and continue.
  - **Strict pipelines**: treat any warning as a hard error by checking
    `result.warnings.is_empty()` before using the output.

  See [`WarningKind`] for the full taxonomy of warning categories.
  """

  @typedoc "A non-fatal diagnostic produced during HTML conversion."
  @type t :: %__MODULE__{
          message: String.t() | nil,
          kind: String.t() | nil
        }

  defstruct message: nil,
            kind: :image_extraction_failed
end
