# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f51492da65728d7d178c7bf5de14a47db4261572db98d390cf0f7dc1b61d309
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc "A non-fatal warning generated during HTML processing."

  @type t :: %__MODULE__{
    message: String.t() | nil,
    kind: String.t() | nil
  }

  defstruct message: nil,
            kind: :image_extraction_failed
end
