# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e08387dc4b300038d4602c7dc3b00bb5504319c2549cc76ea908457546c23c4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule HtmlToMarkdown.StructuredData do
  @moduledoc "Structured data block (JSON-LD, Microdata, or RDFa)."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
