# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e19f5e250479865621565e32ea53c3202125b83874ff092ae603c0e3a3069a19
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  @typedoc "A structured table grid with cell-level data including spans."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [map()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
