# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7f7315ae9786ca9e8f870af4f75d4f4f80b350b3cdf1078712b8959443eaccd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  @typedoc "A structured table grid with cell-level data including spans."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [map()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
