# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3018ac86397d06eb06f0310e148b8377f08cc898c914c7151583d4603b1670d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: map(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
