# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44e2d75463a5dd5fcd6e1eb8848373eac19faf9c1aefbe14a0d4b612acdb99d7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: map(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
