# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:343ebe0b8cb2b70f17247e419c6a21e0940eb11e4428ec2d98aa63d39bd5a9c3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: map(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
