# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a5b3f996ee92f829738c65f0dd7cd71017c0f67468cdb2976b3a3d616a35faee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TextDirection do
  @moduledoc """
  Text directionality of document content.

  Corresponds to the HTML `dir` attribute and `bdi` element directionality.
  """

  @typedoc "Text directionality of document content."
  @type t :: :ltr | :rtl | :auto

  @left_to_right :ltr
  @right_to_left :rtl
  @auto :auto

  @doc "Left-to-right text flow (default for Latin scripts)"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text flow (Hebrew, Arabic, Urdu, etc.)"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic directionality detection"
  @spec auto() :: t()
  def auto, do: @auto
end
