# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:058f46c4a23be631f95892dda1285555d88e130514a84226566de9b275e464cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc """
  Whitespace handling strategy during conversion.

  Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
  """

  @typedoc "Whitespace handling strategy during conversion."
  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @doc "Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior."
  @spec normalized() :: t()
  def normalized, do: @normalized
  @doc "Preserve all whitespace exactly as it appears in the HTML."
  @spec strict() :: t()
  def strict, do: @strict
end
