# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b2349155f7fb028a2f1e87bb52f2e3008131ce2f4c23434c339d2d3b760adfe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc """
  Whitespace handling strategy during conversion.

  Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
  """

  @typedoc "Whitespace handling strategy during conversion."
  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @doc "Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior."
  @spec normalized() :: t()
  def normalized, do: @normalized
  @doc "Preserve all whitespace exactly as it appears in the HTML."
  @spec strict() :: t()
  def strict, do: @strict
end
