// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2f735b70f8035ac75dd76713c43e38b124f54efc531363640bd0eacdb47cc000
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
