// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a570f801d21b83da73e2656ef9ae96018d5af6de128d8e5333d6c359840a891
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
  },
});
