// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bd1d478a876609e345b426e5e912dae989affe44f77db2ce46819460eee7e285
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// Code block fence style in Markdown output./// /// Determines how code blocks (`<pre><code>`) are rendered in Markdown./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CodeBlockStyle
{/// <summary>    /// Indented code blocks (4 spaces). `CommonMark` standard.    /// </summary>
[JsonPropertyName("indented")]
    Indented,/// <summary>    /// Fenced code blocks with backticks (```). Default (GFM). Supports language hints.    /// </summary>
[JsonPropertyName("backticks")]
    Backticks,/// <summary>    /// Fenced code blocks with tildes (~~~). Supports language hints.    /// </summary>
[JsonPropertyName("tildes")]
    Tildes,}
