// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1da055e3cc170122f9709ca046a003279fd9b4ac758533f00d080b7fb9ebc446
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
