// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:63511c69fc7a45137bd835e2964089fe6360c9d92c11093323d38d8128ec0357
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
