// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:19bb30b9ab9930af82136c553420f84eaac0b1ace4e004f52b1309833ff65529
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
