// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7c5ad05ac9e59c595d7daf5f7fabeb16a8558d1e5ee7b1f6354d87928aab04d5
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
