// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:df03cfa1ea58fc063ec7e305db2e9dcdc739bb4b063899fc4750f8584c5bd37e
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
