// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dd20745cb7d85c95c7db5ec4429a3bdd94bf825bf11b006f4f32eaedb94a8b8f
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
