// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8551441404f65abe0889154a4935ec338280b0f250149240000f122bf7744473
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// Heading style options for Markdown output./// /// Controls how headings (h1-h6) are rendered in the output Markdown./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum HeadingStyle
{    /// <summary>    /// Underlined style (=== for h1, --- for h2).    /// </summary>
    [JsonPropertyName("underlined")]
    Underlined,    /// <summary>    /// ATX style (# for h1, ## for h2, etc.). Default.    /// </summary>
    [JsonPropertyName("atx")]
    Atx,    /// <summary>    /// ATX closed style (# title #, with closing hashes).    /// </summary>
    [JsonPropertyName("atxclosed")]
    AtxClosed,}
