// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3aff2ceb5717068a427a96dba542333da6f58dffdf7e407dbeb54f3634546924
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// Highlight rendering style for `<mark>` elements./// /// Controls how highlighted text is rendered in Markdown output./// </summary>
public enum HighlightStyle
{/// <summary>    /// Double equals syntax (==text==). Default. Pandoc-compatible.    /// </summary>
[JsonPropertyName("doubleequal")]
    DoubleEqual,/// <summary>    /// Preserve as HTML (==text==). Original HTML tag.    /// </summary>
[JsonPropertyName("html")]
    Html,/// <summary>    /// Render as bold (**text**). Uses strong emphasis.    /// </summary>
[JsonPropertyName("bold")]
    Bold,/// <summary>    /// Strip formatting, render as plain text. No markup.    /// </summary>
[JsonPropertyName("none")]
    None,}
