// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7b742aec4d3374c69cf313c9d18e3820cfb343d1cf27f1af11ee1da2a9041fe5
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// Highlight rendering style for `<mark>` elements./// /// Controls how highlighted text is rendered in Markdown output./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum HighlightStyle
{/// <summary>    /// Double equals syntax (==text==). Default. Pandoc-compatible.    /// </summary>
[JsonPropertyName("doubleequal")]
    DoubleEqual,/// <summary>    /// Preserve as HTML (==text==). Original HTML tag.    /// </summary>
[JsonPropertyName("html")]
    Html,/// <summary>    /// Render as bold (**text**). Uses strong emphasis.    /// </summary>
[JsonPropertyName("bold")]
    Bold,/// <summary>    /// Strip formatting, render as plain text. No markup.    /// </summary>
[JsonPropertyName("none")]
    None,}
