// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b5f15c7d660ec2562e723c5e72653fb0c720939f1c5d5cc987ea7c6b851d0358
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Comprehensive metadata extraction result from HTML document.
///
/// Contains all extracted metadata types in a single structure,
/// suitable for serialization and transmission across language boundaries.
///
/// # Examples
///
/// ```
/// let metadata = HtmlMetadata {
///     document: Default::default(),
///     headers: Vec::new(),
///     links: Vec::new(),
///     images: Vec::new(),
///     structured_data: Vec::new(),
/// };
///
/// assert!(metadata.headers.is_empty());
/// ```
/// </summary>
public sealed record HtmlMetadata
{
    /// <summary>
    /// Document-level metadata (title, description, canonical, etc.)
    /// </summary>
    [JsonPropertyName("document")]
    public DocumentMetadata Document { get; init; } = default!;

    /// <summary>
    /// Extracted header elements with hierarchy
    /// </summary>
    [JsonPropertyName("headers")]
    public List<HeaderMetadata> Headers { get; init; } = [];

    /// <summary>
    /// Extracted hyperlinks with type classification
    /// </summary>
    [JsonPropertyName("links")]
    public List<LinkMetadata> Links { get; init; } = [];

    /// <summary>
    /// Extracted images with source and dimensions
    /// </summary>
    [JsonPropertyName("images")]
    public List<ImageMetadata> Images { get; init; } = [];

    /// <summary>
    /// Extracted structured data blocks
    /// </summary>
    [JsonPropertyName("structured_data")]
    public List<StructuredData> StructuredData { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="HtmlMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static HtmlMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<HtmlMetadata>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse HtmlMetadata from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse HtmlMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
