// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cd2834af6faec95ba72da53570d99ea0eac38dbafd9303b8cc9c178fc3d201ae
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }

    public HtmlToMarkdownRsException(string message) : base(message)
    {
        Code = 0;
    }

    public HtmlToMarkdownRsException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
