// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fe2faafad5d9f264f214640a6abbd281095c5e3558b650131b1ebee9748d9bc5
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
