// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7c5ad05ac9e59c595d7daf5f7fabeb16a8558d1e5ee7b1f6354d87928aab04d5
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
