// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
