// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
