// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2c49ac946ea672c41dde9e798b56a448c135dec7ce5e86b0112d3a0bbf9f32b9
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
