// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cf678458474e7cafe2c1fbcf03ecd1f1503fd0c3f49876effeea7fe080d9b34e
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
