// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fadcd9eba4e64e5ee8b5169851008c309bcbd73c57ce9d4f6e72442c2dced334
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Link rendering style in Markdown output.
///
/// Controls whether links and images use inline `[text](url)` syntax or
/// reference-style `[text][1]` syntax with definitions collected at the end.
/// </summary>
[JsonConverter(typeof(LinkStyleJsonConverter))]
public enum LinkStyle
{
    /// <summary>
    /// Inline links: `[text](url)`. Default.
    /// </summary>
    [JsonPropertyName("Inline")]
    Inline,
    /// <summary>
    /// Reference-style links: `[text][1]` with `[1]: url` at end of document.
    /// </summary>
    [JsonPropertyName("Reference")]
    Reference,
}


/// <summary>
/// Custom JSON converter for <see cref="LinkStyle"/> that respects explicit variant names.
/// </summary>
internal sealed class LinkStyleJsonConverter : JsonConverter<LinkStyle>
{
    public override LinkStyle Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Inline" => LinkStyle.Inline,
            "Reference" => LinkStyle.Reference,
            _ => throw new JsonException($"Unknown LinkStyle value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, LinkStyle value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            LinkStyle.Inline => "Inline",
            LinkStyle.Reference => "Reference",
            _ => throw new JsonException($"Unknown LinkStyle value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
