// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:535466851b74da93be3b4c8d969cdb3fe19eacb7229a3b877aa4d4b215bd1515
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// Link classification based on href value and document context./// /// Used to categorize links during extraction for filtering and analysis./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LinkType
{    /// <summary>    /// Anchor link within same document (href starts with #)    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,    /// <summary>    /// Internal link within same domain    /// </summary>
    [JsonPropertyName("internal")]
    Internal,    /// <summary>    /// External link to different domain    /// </summary>
    [JsonPropertyName("external")]
    External,    /// <summary>    /// Email link (mailto:)    /// </summary>
    [JsonPropertyName("email")]
    Email,    /// <summary>    /// Phone link (tel:)    /// </summary>
    [JsonPropertyName("phone")]
    Phone,    /// <summary>    /// Other protocol or unclassifiable    /// </summary>
    [JsonPropertyName("other")]
    Other,}
