// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:61b453b7a786e53ba4d5825e8d3180c2025e5069305076e656c256e8b09b64af
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// List indentation character type./// /// Controls whether list items are indented with spaces or tabs./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ListIndentType
{/// <summary>    /// Use spaces for indentation. Default. Width controlled by `list_indent_width`.    /// </summary>
[JsonPropertyName("spaces")]
    Spaces,/// <summary>    /// Use tabs for indentation.    /// </summary>
[JsonPropertyName("tabs")]
    Tabs,}
