// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:989127b804ac463e911e5dd1c9501cfbdd39b5e5f435f39004b9e57ab5331287
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// List indentation character type.
///
/// Controls whether list items are indented with spaces or tabs.
/// </summary>
[JsonConverter(typeof(ListIndentTypeJsonConverter))]
public enum ListIndentType
{
    /// <summary>
    /// Use spaces for indentation. Default. Width controlled by `list_indent_width`.
    /// </summary>
    [JsonPropertyName("spaces")]
    Spaces,
    /// <summary>
    /// Use tabs for indentation.
    /// </summary>
    [JsonPropertyName("tabs")]
    Tabs,
}


/// <summary>
/// Custom JSON converter for <see cref="ListIndentType"/> that respects explicit variant names.
/// </summary>
internal sealed class ListIndentTypeJsonConverter : JsonConverter<ListIndentType>
{
    public override ListIndentType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "spaces" => ListIndentType.Spaces,
            "tabs" => ListIndentType.Tabs,
            _ => throw new JsonException($"Unknown ListIndentType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ListIndentType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ListIndentType.Spaces => "spaces",
            ListIndentType.Tabs => "tabs",
            _ => throw new JsonException($"Unknown ListIndentType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
