// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77a993efaaebae8c3b23a2710d132d1b20b8c70281508df55aa4b842c9bca596
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>Context passed to every visitor callback.</summary>
public record NodeContext(    [property: JsonPropertyName("node_type")] NodeType NodeType,    [property: JsonPropertyName("tag_name")] string TagName,    [property: JsonPropertyName("depth")] ulong Depth,    [property: JsonPropertyName("index_in_parent")] ulong IndexInParent,    [property: JsonPropertyName("parent_tag")] string? ParentTag,    [property: JsonPropertyName("is_inline")] bool IsInline);
