// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8fb4980b8f6485af19b29bb93f64385c7de27e575066bf6889391634150eaecf
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
