// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3288161abcd48034b98a56f9c383276302f3280f3991e1dce8793cf4a7891ca4
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
