// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:84d618befc1fcbd42d1a02ee1ded5dc87dd438dbe303400c2f89891d9475e3f6
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
