// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0c3ad5a882b36385eb49552278543097810607c89b84ce4b299ec2b918abc0d9
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
