// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:77a993efaaebae8c3b23a2710d132d1b20b8c70281508df55aa4b842c9bca596
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
