// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3b2349155f7fb028a2f1e87bb52f2e3008131ce2f4c23434c339d2d3b760adfe
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
