// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fadcd9eba4e64e5ee8b5169851008c309bcbd73c57ce9d4f6e72442c2dced334
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
