// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:20ecfea42a0ee961d9ccc3eb2c536813e3870a7b98a8e85e1d741e5d1860a4b0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// Partial update for `PreprocessingOptions`.
///
/// This struct uses `Option&lt;T&gt;` to represent optional fields that can be selectively updated.
/// Only specified fields (values) will override existing options; null values leave the
/// corresponding fields unchanged when applied via `PreprocessingOptions.apply_update`.
/// </summary>
public sealed record PreprocessingOptionsUpdate
{
    /// <summary>
    /// Optional global preprocessing enablement override
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; } = null;

    /// <summary>
    /// Optional preprocessing preset level override (Minimal, Standard, Aggressive)
    /// </summary>
    [JsonPropertyName("preset")]
    public PreprocessingPreset? Preset { get; init; } = null;

    /// <summary>
    /// Optional navigation element removal override (nav, breadcrumbs, menus, sidebars)
    /// </summary>
    [JsonPropertyName("remove_navigation")]
    public bool? RemoveNavigation { get; init; } = null;

    /// <summary>
    /// Optional form element removal override (forms, inputs, buttons, etc.)
    /// </summary>
    [JsonPropertyName("remove_forms")]
    public bool? RemoveForms { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="PreprocessingOptionsUpdate"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static PreprocessingOptionsUpdate FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<PreprocessingOptionsUpdate>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse PreprocessingOptionsUpdate from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse PreprocessingOptionsUpdate from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
