// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fadcd9eba4e64e5ee8b5169851008c309bcbd73c57ce9d4f6e72442c2dced334
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// HTML preprocessing aggressiveness level.
///
/// Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
/// </summary>
[JsonConverter(typeof(PreprocessingPresetJsonConverter))]
public enum PreprocessingPreset
{
    /// <summary>
    /// Minimal cleanup. Remove only essential noise (scripts, styles).
    /// </summary>
    [JsonPropertyName("Minimal")]
    Minimal,
    /// <summary>
    /// Standard cleanup. Default. Removes navigation, forms, and other auxiliary content.
    /// </summary>
    [JsonPropertyName("Standard")]
    Standard,
    /// <summary>
    /// Aggressive cleanup. Remove extensive non-content elements and structure.
    /// </summary>
    [JsonPropertyName("Aggressive")]
    Aggressive,
}


/// <summary>
/// Custom JSON converter for <see cref="PreprocessingPreset"/> that respects explicit variant names.
/// </summary>
internal sealed class PreprocessingPresetJsonConverter : JsonConverter<PreprocessingPreset>
{
    public override PreprocessingPreset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Minimal" => PreprocessingPreset.Minimal,
            "Standard" => PreprocessingPreset.Standard,
            "Aggressive" => PreprocessingPreset.Aggressive,
            _ => throw new JsonException($"Unknown PreprocessingPreset value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, PreprocessingPreset value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            PreprocessingPreset.Minimal => "Minimal",
            PreprocessingPreset.Standard => "Standard",
            PreprocessingPreset.Aggressive => "Aggressive",
            _ => throw new JsonException($"Unknown PreprocessingPreset value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
