// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5ace88c020e907e933880c587b5b5aaf6b605c8da9334cf85de36e4210601cea
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
