// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1d54d668be048c4e75a97b3e3e35291bd9b0a7f9be8eb79a6a22f856594bc8bd
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
