// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9077483349c7e22ecea0cc8a1933a818959f53868e93afd573c693b5012f3909
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A top-level extracted table with both structured data and markdown representation.
/// </summary>
public sealed class TableData
{
    /// <summary>
    /// The structured table grid.
    /// </summary>
    [JsonPropertyName("grid")]
    public TableGrid Grid { get; set; } = default!;

    /// <summary>
    /// The markdown rendering of this table.
    /// </summary>
    [JsonPropertyName("markdown")]
    public string Markdown { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="TableData"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static TableData FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<TableData>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse TableData from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse TableData from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
