// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a7fbf0675617f3907e53c41862991c46c40b22d37e4426365e9d6b715355129
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// An inline text annotation with byte-range offsets.
///
/// Annotations describe formatting (bold, italic, etc.) and links within a node's text content.
/// </summary>
public sealed record TextAnnotation
{
    /// <summary>
    /// Start byte offset (inclusive) into the parent node's text.
    /// </summary>
    [JsonPropertyName("start")]
    public uint Start { get; init; } = 0;

    /// <summary>
    /// End byte offset (exclusive) into the parent node's text.
    /// </summary>
    [JsonPropertyName("end")]
    public uint End { get; init; } = 0;

    /// <summary>
    /// The type of annotation.
    /// </summary>
    [JsonPropertyName("kind")]
    public required AnnotationKind Kind { get; init; }


    /// <summary>
    /// Parse a <see cref="TextAnnotation"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static TextAnnotation FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<TextAnnotation>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse TextAnnotation from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse TextAnnotation from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
