// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:60ec9ee521e148c8211e1b0f7b3e13ce9f055ff4cc50b7512cf59c8664a429a6
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace HtmlToMarkdown;

internal sealed class VisitorHandleSafeHandle : SafeHandle
{
    internal VisitorHandleSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.VisitorHandleFree(handle);
        return true;
    }
}
/// <summary>/// Type alias for a visitor handle (`Arc`-wrapped `Mutex` for thread-safe shared mutation)./// /// `Send + Sync` so that types embedding a `VisitorHandle` (e.g. `ConversionOptions`)/// can be shared across threads — required by callers that stash configs inside/// axum/rmcp/tokio Send-bound contexts./// </summary>
public sealed class VisitorHandle : IDisposable
{
    private readonly VisitorHandleSafeHandle _safeHandle;

    internal VisitorHandle(IntPtr handle)
    {
        _safeHandle = new VisitorHandleSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
