// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:84a16bb31c143b85d506c1cd4896118af3d1521780e447164c6e7c3552e34a52
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>/// Whitespace handling strategy during conversion./// /// Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum WhitespaceMode
{/// <summary>    /// Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.    /// </summary>
[JsonPropertyName("normalized")]
    Normalized,/// <summary>    /// Preserve all whitespace exactly as it appears in the HTML.    /// </summary>
[JsonPropertyName("strict")]
    Strict,}
