# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9664cce23f34ebb1892e8ff0cf055a84db187fc3e7376d4266d540b27487ddd7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
"""Exception hierarchy."""


class ConversionError(Exception):
    """Errors that can occur during HTML to Markdown conversion."""


class ParseError(ConversionError):
    """HTML parsing error."""


class SanitizationError(ConversionError):
    """HTML sanitization error."""


class ConfigError(ConversionError):
    """Invalid configuration."""


class IoError(ConversionError):
    """I/O error."""


class PanicError(ConversionError):
    """Panic caught during conversion to prevent unwinding across FFI boundaries."""


class InvalidInputError(ConversionError):
    """Invalid input data."""


class OtherError(ConversionError):
    """Generic conversion error."""
