# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3018ac86397d06eb06f0310e148b8377f08cc898c914c7151583d4603b1670d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy."""


class ConversionError(Exception):
    """Errors that can occur during HTML to Markdown conversion."""


class ParseError(ConversionError):
    """HTML parsing error."""


class SanitizationError(ConversionError):
    """HTML sanitization error."""


class ConfigError(ConversionError):
    """Invalid configuration."""


class IoError(ConversionError):
    """I/O error -- stores the error message string so the variant is FFI-safe."""


class PanicError(ConversionError):
    """Panic caught during conversion to prevent unwinding across FFI boundaries."""


class InvalidInputError(ConversionError):
    """Invalid input data."""


class OtherError(ConversionError):
    """Generic conversion error."""
