# Generated by extendr: Do not edit by hand
# This file is regenerated by alef on every `alef generate` run.

NULL

#' @param html — the HTML string to convert.
#' @param options — conversion options. Rust accepts bare [`ConversionOptions`], `Some(options)`, or `None`. Language bindings expose the same option fields through native constructors or optional parameters.
#' @return ConversionResult object (list with class attribute).
convert <- function(html, options = ConversionOptions$default()) .Call("wrap__convert", html, options, PACKAGE = "htmltomarkdown")
DocumentMetadata <- new.env(parent = emptyenv())
DocumentMetadata$from_json <- function(json) {
  .Call("wrap__DocumentMetadata__from_json", json, PACKAGE = "htmltomarkdown")
}
`$.DocumentMetadata` <- function(self, name) {
  func <- DocumentMetadata[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.DocumentMetadata` <- `$.DocumentMetadata`
HeaderMetadata <- new.env(parent = emptyenv())
HeaderMetadata$is_valid <- function(self) .Call("wrap__HeaderMetadata__is_valid", self, PACKAGE = "htmltomarkdown")
`$.HeaderMetadata` <- function(self, name) {
  func <- HeaderMetadata[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.HeaderMetadata` <- `$.HeaderMetadata`
is_valid.HeaderMetadata <- function(x, ...) x$is_valid(...)
LinkMetadata <- new.env(parent = emptyenv())
`$.LinkMetadata` <- function(self, name) {
  func <- LinkMetadata[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.LinkMetadata` <- `$.LinkMetadata`
ImageMetadata <- new.env(parent = emptyenv())
`$.ImageMetadata` <- function(self, name) {
  func <- ImageMetadata[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.ImageMetadata` <- `$.ImageMetadata`
StructuredData <- new.env(parent = emptyenv())
`$.StructuredData` <- function(self, name) {
  func <- StructuredData[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.StructuredData` <- `$.StructuredData`
ConversionOptions <- new.env(parent = emptyenv())
ConversionOptions$default <- function() .Call("wrap__ConversionOptions__default", PACKAGE = "htmltomarkdown")
ConversionOptions$from_json <- function(json) {
  .Call("wrap__ConversionOptions__from_json", json, PACKAGE = "htmltomarkdown")
}
`$.ConversionOptions` <- function(self, name) {
  func <- ConversionOptions[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.ConversionOptions` <- `$.ConversionOptions`
ConversionOptionsUpdate <- new.env(parent = emptyenv())
`$.ConversionOptionsUpdate` <- function(self, name) {
  func <- ConversionOptionsUpdate[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.ConversionOptionsUpdate` <- `$.ConversionOptionsUpdate`
PreprocessingOptions <- new.env(parent = emptyenv())
PreprocessingOptions$default <- function() .Call("wrap__PreprocessingOptions__default", PACKAGE = "htmltomarkdown")
PreprocessingOptions$from_json <- function(json) {
  .Call("wrap__PreprocessingOptions__from_json", json, PACKAGE = "htmltomarkdown")
}
`$.PreprocessingOptions` <- function(self, name) {
  func <- PreprocessingOptions[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.PreprocessingOptions` <- `$.PreprocessingOptions`
PreprocessingOptionsUpdate <- new.env(parent = emptyenv())
`$.PreprocessingOptionsUpdate` <- function(self, name) {
  func <- PreprocessingOptionsUpdate[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.PreprocessingOptionsUpdate` <- `$.PreprocessingOptionsUpdate`
ImageDimensions <- new.env(parent = emptyenv())
`$.ImageDimensions` <- function(self, name) {
  func <- ImageDimensions[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.ImageDimensions` <- `$.ImageDimensions`
TextAnnotation <- new.env(parent = emptyenv())
`$.TextAnnotation` <- function(self, name) {
  func <- TextAnnotation[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.TextAnnotation` <- `$.TextAnnotation`
MetadataEntry <- new.env(parent = emptyenv())
`$.MetadataEntry` <- function(self, name) {
  func <- MetadataEntry[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.MetadataEntry` <- `$.MetadataEntry`
GridCell <- new.env(parent = emptyenv())
`$.GridCell` <- function(self, name) {
  func <- GridCell[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.GridCell` <- `$.GridCell`
TableData <- new.env(parent = emptyenv())
`$.TableData` <- function(self, name) {
  func <- TableData[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.TableData` <- `$.TableData`
ProcessingWarning <- new.env(parent = emptyenv())
`$.ProcessingWarning` <- function(self, name) {
  func <- ProcessingWarning[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.ProcessingWarning` <- `$.ProcessingWarning`
NodeContext <- new.env(parent = emptyenv())
NodeContext$into_owned <- function(self) .Call("wrap__NodeContext__into_owned", self, PACKAGE = "htmltomarkdown")
`$.NodeContext` <- function(self, name) {
  func <- NodeContext[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.NodeContext` <- `$.NodeContext`
into_owned.NodeContext <- function(x, ...) x$into_owned(...)
VisitResult <- new.env(parent = emptyenv())
`$.VisitResult` <- function(self, name) {
  func <- VisitResult[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.VisitResult` <- `$.VisitResult`
#' @return A TextDirection enum value
TextDirection  <- function() list() |> structure(class = "TextDirection")
#' @return A LinkType enum value
LinkType  <- function() list() |> structure(class = "LinkType")
#' @return A ImageType enum value
ImageType  <- function() list() |> structure(class = "ImageType")
#' @return A StructuredDataType enum value
StructuredDataType  <- function() list() |> structure(class = "StructuredDataType")
#' @return A TierStrategy enum value
TierStrategy  <- function() list() |> structure(class = "TierStrategy")
#' @return A PreprocessingPreset enum value
PreprocessingPreset  <- function() list() |> structure(class = "PreprocessingPreset")
#' @return A HeadingStyle enum value
HeadingStyle  <- function() list() |> structure(class = "HeadingStyle")
#' @return A ListIndentType enum value
ListIndentType  <- function() list() |> structure(class = "ListIndentType")
#' @return A WhitespaceMode enum value
WhitespaceMode  <- function() list() |> structure(class = "WhitespaceMode")
#' @return A NewlineStyle enum value
NewlineStyle  <- function() list() |> structure(class = "NewlineStyle")
#' @return A CodeBlockStyle enum value
CodeBlockStyle  <- function() list() |> structure(class = "CodeBlockStyle")
#' @return A HighlightStyle enum value
HighlightStyle  <- function() list() |> structure(class = "HighlightStyle")
#' @return A LinkStyle enum value
LinkStyle  <- function() list() |> structure(class = "LinkStyle")
#' @return A UrlEscapeStyle enum value
UrlEscapeStyle  <- function() list() |> structure(class = "UrlEscapeStyle")
#' @return A OutputFormat enum value
OutputFormat  <- function() list() |> structure(class = "OutputFormat")
#' @return A WarningKind enum value
WarningKind  <- function() list() |> structure(class = "WarningKind")
#' @return A NodeType enum value
NodeType  <- function() list() |> structure(class = "NodeType")
NodeContent <- new.env(parent = emptyenv())
NodeContent$default <- function() .Call("wrap__NodeContent__default", PACKAGE = "htmltomarkdown")
NodeContent$from_json <- function(json) .Call("wrap__NodeContent__from_json", json, PACKAGE = "htmltomarkdown")
NodeContent$heading <- function(level, text) .Call("wrap__NodeContent___factory_heading", level, text, PACKAGE = "htmltomarkdown")
NodeContent$paragraph <- function(text) .Call("wrap__NodeContent___factory_paragraph", text, PACKAGE = "htmltomarkdown")
NodeContent$list <- function(ordered) .Call("wrap__NodeContent___factory_list", ordered, PACKAGE = "htmltomarkdown")
NodeContent$list_item <- function(text) .Call("wrap__NodeContent___factory_list_item", text, PACKAGE = "htmltomarkdown")
NodeContent$image <- function(description, src, image_index) .Call("wrap__NodeContent___factory_image", description, src, image_index, PACKAGE = "htmltomarkdown")
NodeContent$code <- function(text, language) .Call("wrap__NodeContent___factory_code", text, language, PACKAGE = "htmltomarkdown")
NodeContent$definition_item <- function(term, definition) .Call("wrap__NodeContent___factory_definition_item", term, definition, PACKAGE = "htmltomarkdown")
NodeContent$raw_block <- function(format, content) .Call("wrap__NodeContent___factory_raw_block", format, content, PACKAGE = "htmltomarkdown")
NodeContent$group <- function(label, heading_level, heading_text) .Call("wrap__NodeContent___factory_group", label, heading_level, heading_text, PACKAGE = "htmltomarkdown")
`$.NodeContent` <- function(self, name) {
  func <- NodeContent[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.NodeContent` <- `$.NodeContent`
AnnotationKind <- new.env(parent = emptyenv())
AnnotationKind$default <- function() .Call("wrap__AnnotationKind__default", PACKAGE = "htmltomarkdown")
AnnotationKind$from_json <- function(json) .Call("wrap__AnnotationKind__from_json", json, PACKAGE = "htmltomarkdown")
AnnotationKind$link <- function(url, title) .Call("wrap__AnnotationKind___factory_link", url, title, PACKAGE = "htmltomarkdown")
`$.AnnotationKind` <- function(self, name) {
  func <- AnnotationKind[[name]]
  if (identical(names(formals(func))[1], "self")) {
    function(...) func(self, ...)
  } else {
    func
  }
}
`[[.AnnotationKind` <- `$.AnnotationKind`
into_owned <- function(x, ...) UseMethod("into_owned")
is_valid <- function(x, ...) UseMethod("is_valid")
