# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c774a47002bd6562e18689c654c801403060527a5e233b8d429a4d4e0b336884
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL

#' Convert HTML to Markdown, returning a [`ConversionResult`] with content, metadata, images,
#' and warnings.
#'
#' # Arguments
#'
#' * `html` - The HTML string to convert
#' * `options` - Optional conversion options (defaults to `ConversionOptions::default()`)
#'
#' # Example
#'
#' ```
#' use html_to_markdown_rs::{convert, ConversionOptions};
#'
#' let html = "<h1>Hello World</h1>";
#' let result = convert(html, None, None).unwrap();
#' assert!(result.content.as_deref().unwrap_or("").contains("Hello World"));
#' ```
#'
#' # Errors
#'
#' Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
#' @export
convert <- function(html, options = NULL, visitor = NULL) {
  .Call("htm_convert", html, options, visitor)
}
