# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf678458474e7cafe2c1fbcf03ecd1f1503fd0c3f49876effeea7fe080d9b34e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL
