# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0e6af9fe284c69f97523ccc80f1bf1e4c5eab16c374ccf736100cd19f66cf01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL
