# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:058f46c4a23be631f95892dda1285555d88e130514a84226566de9b275e464cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_empty_string: Empty string produces empty output' do
    result = HtmlToMarkdown.convert('')
    expect(result.content.to_s.strip).to eq(''.strip)

  end

  it 'smoke_simple_heading: H1 heading converts to ATX markdown' do
    result = HtmlToMarkdown.convert('<h1>Title</h1>')
    expect(result.content.to_s).to include('# Title')

  end

  it 'smoke_simple_paragraph: Simple paragraph converts correctly' do
    result = HtmlToMarkdown.convert('<p>Hello World</p>')
    expect(result.content.to_s.strip).to eq('Hello World'.strip)
    expect(result.content.to_s).not_to be_empty

  end
end
