# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7f7b6241038275ef18324bb45363638cfc6f66b6b90bdd01883fa579ce0279f4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
