# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f735b70f8035ac75dd76713c43e38b124f54efc531363640bd0eacdb47cc000
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
