# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fadcd9eba4e64e5ee8b5169851008c309bcbd73c57ce9d4f6e72442c2dced334
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
