// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:343ebe0b8cb2b70f17247e419c6a21e0940eb11e4428ec2d98aa63d39bd5a9c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Code block fence style in Markdown output.
 *
 * Determines how code blocks ({@code &lt;pre&gt;&lt;code&gt;}) are rendered in Markdown.
 */
@SuppressWarnings("PMD")
public enum CodeBlockStyle {
    /**
     * Indented code blocks (4 spaces). {@code CommonMark} standard.
     */
    Indented("indented"),
    /**
     * Fenced code blocks with backticks ({@code }{@code ). Default (GFM). Supports language hints.}
     */
    Backticks("backticks"),
    /**
     * Fenced code blocks with tildes (~~~). Supports language hints.
     */
    Tildes("tildes");


    /** The string value. */
    private final String value;

    CodeBlockStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CodeBlockStyle fromValue(final String value) {
        for (CodeBlockStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown CodeBlockStyle value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
