// DO NOT EDIT - auto-generated by alef
// alef:hash:343ebe0b8cb2b70f17247e419c6a21e0940eb11e4428ec2d98aa63d39bd5a9c3
package dev.kreuzberg.htmltomarkdown;

/**
 * Invalid configuration
 */
public class ConfigErrorException extends ConversionErrorException {
    /** Creates a new ConfigErrorException with the given message. */
    public ConfigErrorException(final String message) {
        super(message);
    }

    /** Creates a new ConfigErrorException with the given message and cause. */
    public ConfigErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
