// DO NOT EDIT - auto-generated by alef
// alef:hash:b02c788745b375401daf19102376d59d2057f4ad3b5399fd76bd12fad0005c44
package dev.kreuzberg.htmltomarkdown;

/**
 * Invalid configuration
 */
public class ConfigErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigErrorException with the given message. */
  public ConfigErrorException(final String message) {
    super(message);
  }

  /** Creates a new ConfigErrorException with the given message and cause. */
  public ConfigErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
