// DO NOT EDIT - auto-generated by alef
// alef:hash:2c49ac946ea672c41dde9e798b56a448c135dec7ce5e86b0112d3a0bbf9f32b9
package dev.kreuzberg.htmltomarkdown;

/**
 * Invalid configuration
 */
public class ConfigErrorException extends ConversionErrorException {
    /** Creates a new ConfigErrorException with the given message. */
    public ConfigErrorException(final String message) {
        super(message);
    }

    /** Creates a new ConfigErrorException with the given message and cause. */
    public ConfigErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
