// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff98db01807f9f95c384bd06a6d0bdad26dcedddf2cca63d4635fdb379926864
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Document-level metadata extracted from {@code &lt;head&gt;} and top-level elements.
 *
 * Contains all metadata typically used by search engines, social media platforms,
 * and browsers for document indexing and presentation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocumentMetadataBuilder.class)
public record DocumentMetadata(
    @Nullable String title,
    @Nullable String description,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> keywords,
    @Nullable String author,
    @Nullable @JsonProperty("canonical_url") String canonicalUrl,
    @Nullable @JsonProperty("base_href") String baseHref,
    @Nullable String language,
    @Nullable @JsonProperty("text_direction") TextDirection textDirection,
    @JsonProperty("open_graph") Map<String, String> openGraph,
    @JsonProperty("twitter_card") Map<String, String> twitterCard,
    @JsonProperty("meta_tags") Map<String, String> metaTags
) {
    public static DocumentMetadataBuilder builder() {
        return new DocumentMetadataBuilder();
    }
}
