// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:edcc0d3098122340850c5c6389de3f7242d588161311b7b4f7d0805d404cde04
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single cell in a table grid.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record GridCell(String content, int row, int col, @JsonProperty("rowSpan") int rowSpan,
        @JsonProperty("colSpan") int colSpan, @JsonProperty("isHeader") boolean isHeader) {

    /**
     * Parse a {@code GridCell} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException
     *             if the JSON cannot be deserialised.
     */
    public static GridCell fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, GridCell.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse GridCell from JSON: " + e.getMessage(), e);
        }
    }
}
