// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cf678458474e7cafe2c1fbcf03ecd1f1503fd0c3f49876effeea7fe080d9b34e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Heading style options for Markdown output.
 *
 * Controls how headings (h1-h6) are rendered in the output Markdown.
 */
@SuppressWarnings("PMD")
public enum HeadingStyle {
    /**
     * Underlined style (=== for h1, --- for h2).
     */
    Underlined("underlined"),
    /**
     * ATX style (# for h1, ## for h2, etc.). Default.
     */
    Atx("atx"),
    /**
     * ATX closed style (# title #, with closing hashes).
     */
    AtxClosed("atxclosed");


    /** The string value. */
    private final String value;

    HeadingStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static HeadingStyle fromValue(final String value) {
        for (HeadingStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown HeadingStyle value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
