// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4f6b7744dcf0f1f06f9527cf0341db5c31f5848b53b82c7af2db63440e7fabd7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new HtmlToMarkdownRsException. */
  public HtmlToMarkdownRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new HtmlToMarkdownRsException with a cause. */
  public HtmlToMarkdownRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
