// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new HtmlToMarkdownRsException. */
  public HtmlToMarkdownRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new HtmlToMarkdownRsException with a cause. */
  public HtmlToMarkdownRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
