// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cf678458474e7cafe2c1fbcf03ecd1f1503fd0c3f49876effeea7fe080d9b34e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class HtmlToMarkdownRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new HtmlToMarkdownRsException. */
    public HtmlToMarkdownRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new HtmlToMarkdownRsException with a cause. */
    public HtmlToMarkdownRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
