// DO NOT EDIT - auto-generated by alef
// alef:hash:585c7ebe9e143ecddb26d8c355cfffd7a24a39547485dcb8ef6b8ba2316e8d41
package dev.kreuzberg.htmltomarkdown;

/**
 * I/O error — stores the error message string so the variant is FFI-safe.
 *
 * Use `ConversionError::from(io_error)` to convert from `std::io::Error`.
 */
public class IoErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoErrorException with the given message. */
  public IoErrorException(final String message) {
    super(message);
  }

  /** Creates a new IoErrorException with the given message and cause. */
  public IoErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
