// DO NOT EDIT - auto-generated by alef
// alef:hash:799eef04d4b094da2cdf40adc99bb911321f97019685cdbc5027857b4c977b62
package dev.kreuzberg.htmltomarkdown;

/**
 * I/O error — stores the error message string so the variant is FFI-safe.
 *
 * Use `ConversionError::from(io_error)` to convert from `std::io::Error`.
 */
public class IoErrorException extends ConversionErrorException {
    /** Creates a new IoErrorException with the given message. */
    public IoErrorException(final String message) {
        super(message);
    }

    /** Creates a new IoErrorException with the given message and cause. */
    public IoErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
