// DO NOT EDIT - auto-generated by alef
// alef:hash:e7c33d4f743244048d611effa490326b8bcd4c28caab2a348e78c65dff1e788f
package dev.kreuzberg.htmltomarkdown;

/**
 * I/O error
 */
public class IoErrorException extends ConversionErrorException {
    /** Creates a new IoErrorException with the given message. */
    public IoErrorException(final String message) {
        super(message);
    }

    /** Creates a new IoErrorException with the given message and cause. */
    public IoErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
