// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fadcd9eba4e64e5ee8b5169851008c309bcbd73c57ce9d4f6e72442c2dced334
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link rendering style in Markdown output.
 *
 * Controls whether links and images use inline {@code [text](url)} syntax or
 * reference-style {@code [text][1]} syntax with definitions collected at the end.
 */
public enum LinkStyle {
    /**
     * Inline links: {@code [text](url)}. Default.
     */
    Inline("inline"),
    /**
     * Reference-style links: {@code [text][1]} with {@code [1]: url} at end of document.
     */
    Reference("reference");

    /** The string value. */
    private final String value;

    LinkStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static LinkStyle fromValue(final String value) {
        for (LinkStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
