// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ee9d33743e33433b9fa64a557b46896347d0bb4efa4258b9ad47df5988767a23
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Hyperlink metadata with categorization and attributes.
 *
 * Represents {@code &lt;a&gt;} elements with parsed href values, text content, and link type classification.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LinkMetadata(
    /**
     * The href URL value
     */
    String href,
    /**
     * Link text content (normalized, concatenated if mixed with elements)
     */
    String text,
    /**
     * Optional title attribute (often shown as tooltip)
     */
    @Nullable String title,
    /**
     * Link type classification
     */
    @JsonProperty("link_type") LinkType linkType,
    /**
     * Rel attribute values (e.g., "nofollow", "stylesheet", "canonical")
     */
    List<String> rel,
    /**
     * Additional HTML attributes
     */
    Map<String, String> attributes
) {
}
