// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * List indentation character type.
 *
 * Controls whether list items are indented with spaces or tabs.
 */
@SuppressWarnings("PMD")
public enum ListIndentType {
    /**
     * Use spaces for indentation. Default. Width controlled by {@code list_indent_width}.
     */
    Spaces("spaces"),
    /**
     * Use tabs for indentation.
     */
    Tabs("tabs");


    /** The string value. */
    private final String value;

    ListIndentType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ListIndentType fromValue(final String value) {
        for (ListIndentType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ListIndentType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
