// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44e2d75463a5dd5fcd6e1eb8848373eac19faf9c1aefbe14a0d4b612acdb99d7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

/** Context passed to every visitor callback. */
public record NodeContext(
        /** Coarse-grained node type tag. */
        int nodeType,
        /** HTML element tag name (e.g. "div"). */
        String tagName,
        /** DOM depth (0 = root). */
        long depth,
        /** 0-based sibling index. */
        long indexInParent,
        /** Parent element tag name, or null at the root. */
        String parentTag,
        /** True when this element is treated as inline. */
        boolean isInline
) {}
