// DO NOT EDIT - auto-generated by alef
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
package dev.kreuzberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
