// DO NOT EDIT - auto-generated by alef
// alef:hash:3c6207c3ca07f462c7153c354b98cb895061fc623e2655bf7b92ce8738b5d167
package dev.kreuzberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
