// DO NOT EDIT - auto-generated by alef
// alef:hash:b66e63bedbe733cdfecdde47f2dd4d3e56c53a31eafbcf1e90f990a2eeeed9ab
package dev.kreuzberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
