// DO NOT EDIT - auto-generated by alef
// alef:hash:77a993efaaebae8c3b23a2710d132d1b20b8c70281508df55aa4b842c9bca596
package dev.kreuzberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PanicException with the given message. */
  public PanicException(final String message) {
    super(message);
  }

  /** Creates a new PanicException with the given message and cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
