// DO NOT EDIT - auto-generated by alef
// alef:hash:2f735b70f8035ac75dd76713c43e38b124f54efc531363640bd0eacdb47cc000
package dev.kreuzberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
    /** Creates a new PanicException with the given message. */
    public PanicException(final String message) {
        super(message);
    }

    /** Creates a new PanicException with the given message and cause. */
    public PanicException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
