// DO NOT EDIT - auto-generated by alef
// alef:hash:1da055e3cc170122f9709ca046a003279fd9b4ac758533f00d080b7fb9ebc446
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML parsing error
 */
public class ParseErrorException extends ConversionErrorException {
    /** Creates a new ParseErrorException with the given message. */
    public ParseErrorException(final String message) {
        super(message);
    }

    /** Creates a new ParseErrorException with the given message and cause. */
    public ParseErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
