// DO NOT EDIT - auto-generated by alef
// alef:hash:8fb4980b8f6485af19b29bb93f64385c7de27e575066bf6889391634150eaecf
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML parsing error
 */
public class ParseErrorException extends ConversionErrorException {
    /** Creates a new ParseErrorException with the given message. */
    public ParseErrorException(final String message) {
        super(message);
    }

    /** Creates a new ParseErrorException with the given message and cause. */
    public ParseErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
