// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b729180663d832d37279574641ffafd1da608fd04b4a4296f7aec7875cf9ac4c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * HTML preprocessing options for document cleanup before conversion.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PreprocessingOptionsBuilder.class)
public record PreprocessingOptions(boolean enabled, PreprocessingPreset preset,
        @JsonProperty("remove_navigation") boolean removeNavigation,
        @JsonProperty("remove_forms") boolean removeForms) {
    public static PreprocessingOptionsBuilder builder() {
        return new PreprocessingOptionsBuilder();
    }

    /**
     * Parse a {@code PreprocessingOptions} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException
     *             if the JSON cannot be deserialised.
     */
    public static PreprocessingOptions fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, PreprocessingOptions.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse PreprocessingOptions from JSON: " + e.getMessage(), e);
        }
    }
}
