// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:507cdddea11217c6b8fb2e99d73f615d6743cce24329d77a6b3c347ede8905bd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Partial update for {@code PreprocessingOptions}.
 *
 * This struct uses {@code Option&lt;T&gt;} to represent optional fields that can be selectively updated.
 * Only specified fields (Some values) will override existing options; None values leave the
 * corresponding fields unchanged when applied via PreprocessingOptions::apply_update.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PreprocessingOptionsUpdateBuilder.class)
public record PreprocessingOptionsUpdate(
    @Nullable Boolean enabled,
    @Nullable PreprocessingPreset preset,
    @Nullable @JsonProperty("remove_navigation") Boolean removeNavigation,
    @Nullable @JsonProperty("remove_forms") Boolean removeForms
) {
    public static PreprocessingOptionsUpdateBuilder builder() {
        return new PreprocessingOptionsUpdateBuilder();
    }
}
