// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8628c59cbd5883bb2c4aacba51940c4b51e2bf93b18e88d0348873784f1d20f8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A non-fatal warning generated during HTML processing.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ProcessingWarning(String message, WarningKind kind) {
}
