// DO NOT EDIT - auto-generated by alef
// alef:hash:585c7ebe9e143ecddb26d8c355cfffd7a24a39547485dcb8ef6b8ba2316e8d41
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SanitizationErrorException with the given message. */
  public SanitizationErrorException(final String message) {
    super(message);
  }

  /** Creates a new SanitizationErrorException with the given message and cause. */
  public SanitizationErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
