// DO NOT EDIT - auto-generated by alef
// alef:hash:fadcd9eba4e64e5ee8b5169851008c309bcbd73c57ce9d4f6e72442c2dced334
package dev.kreuzberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
    /** Creates a new SanitizationErrorException with the given message. */
    public SanitizationErrorException(final String message) {
        super(message);
    }

    /** Creates a new SanitizationErrorException with the given message and cause. */
    public SanitizationErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
