// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:85c60dc10ce4fab5e5759c8a55017d3159ca720dc314cf57513058a696f16242
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Structured data block (JSON-LD, Microdata, or RDFa).
 *
 * Represents machine-readable structured data found in the document. JSON-LD blocks are collected as raw JSON strings
 * for flexibility.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredData(@JsonProperty("dataType") StructuredDataType dataType,
        @JsonProperty("rawJson") String rawJson, @Nullable @JsonProperty("schemaType") String schemaType) {

    /**
     * Parse a {@code StructuredData} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException
     *             if the JSON cannot be deserialised.
     */
    public static StructuredData fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, StructuredData.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse StructuredData from JSON: " + e.getMessage(), e);
        }
    }
}
