// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:633ee781c71b806526a450142cec8710ddf8395d3aa3530afdc33a3bd5158d81
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A top-level extracted table with both structured data and markdown representation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TableData(TableGrid grid, String markdown) {

    /**
     * Parse a {@code TableData} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws HtmlToMarkdownRsException
     *             if the JSON cannot be deserialised.
     */
    public static TableData fromJson(String json) throws HtmlToMarkdownRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, TableData.class);
        } catch (Exception e) {
            throw new HtmlToMarkdownRsException("Failed to parse TableData from JSON: " + e.getMessage(), e);
        }
    }
}
