// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A top-level extracted table with both structured data and markdown representation.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TableData.Builder.class)
@SuppressWarnings("PMD")
public record TableData(
    @JsonProperty("grid") TableGrid grid,
    @JsonProperty("markdown") String markdown
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private TableGrid grid = null;
private String markdown = "";

        /** Sets the grid field. */
        @JsonProperty("grid")
        public Builder withGrid(final TableGrid value) {
            this.grid = value;
            return this;
        }

        /** Sets the markdown field. */
        @JsonProperty("markdown")
        public Builder withMarkdown(final String value) {
            this.markdown = value;
            return this;
        }

        /** Builds the TableData instance. */
        public TableData build() {
            return new TableData(
                grid,
                markdown
            );
        }
    }
    // CPD-ON
}
