// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7a17843699ae58ecdab45276ab8539da058c5ef81065f3b146250c79aa0b8898
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Text directionality of document content.
 *
 * Corresponds to the HTML {@code dir} attribute and {@code bdi} element directionality.
 */
public enum TextDirection {
    /** Left-to-right text flow (default for Latin scripts) */
    LeftToRight("ltr"),
    /** Right-to-left text flow (Hebrew, Arabic, Urdu, etc.) */
    RightToLeft("rtl"),
    /** Automatic directionality detection */
    Auto("auto");

    /** The string value. */
    private final String value;

    TextDirection(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static TextDirection fromValue(final String value) {
        for (TextDirection e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
