// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4ba300ecbb725eb266bbcd4f47e9bc50e560372ba8b6f9d9f93c785e8758cdc8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Text directionality of document content.
 *
 * Corresponds to the HTML {@code dir} attribute and {@code bdi} element directionality.
 */
@SuppressWarnings("PMD")
public enum TextDirection {
    /**
     * Left-to-right text flow (default for Latin scripts)
     */
    LeftToRight("ltr"),
    /**
     * Right-to-left text flow (Hebrew, Arabic, Urdu, etc.)
     */
    RightToLeft("rtl"),
    /**
     * Automatic directionality detection
     */
    Auto("auto");


    /** The string value. */
    private final String value;

    TextDirection(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static TextDirection fromValue(final String value) {
        for (TextDirection e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown TextDirection value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
