// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2d34c9be5ddd8539d494385d28cc0187eb8d83ae7cc2f065d732177cb6e2287b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import java.lang.foreign.MemorySegment;

/**
 * Shareable, thread-safe handle to a user-provided HTML visitor implementation.
 *
 * Pass an instance wrapped in this handle to {@code ConversionOptions} to
 * customise how the HTML document is traversed and converted to Markdown.
 * The handle may be cloned and shared across threads without additional
 * synchronisation on the caller's side.
 */
@SuppressWarnings("PMD")
public class VisitorHandle implements AutoCloseable {
    private final MemorySegment handle;

    VisitorHandle(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }
    @Override
    @SuppressWarnings("PMD.AvoidCatchingGenericException")
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.HTM_VISITOR_HANDLE_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free VisitorHandle: " + e.getMessage(), e);
            }
        }
    }
}
