// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

/** Controls how the visitor affects the conversion pipeline. */
@SuppressWarnings("PMD")
public sealed interface VisitResult
        permits VisitResult.Continue, VisitResult.Custom, VisitResult.Skip, VisitResult.PreserveHtml, VisitResult.Error {

    record Continue() implements VisitResult {}

    static VisitResult continue_() {
        return new Continue();
    }
    record Custom(String value) implements VisitResult {}

    static VisitResult custom(String value) {
        return new Custom(value);
    }
    record Skip() implements VisitResult {}

    static VisitResult skip() {
        return new Skip();
    }
    record PreserveHtml() implements VisitResult {}

    static VisitResult preserveHtml() {
        return new PreserveHtml();
    }
    record Error(String value) implements VisitResult {}

    static VisitResult error(String value) {
        return new Error(value);
    }
}
