// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e7406b251a3efb4557c9059248343f2f30ba7f5ba60c54ff22fbf3822397a968
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whitespace handling strategy during conversion.
 *
 * Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
 */
@SuppressWarnings("checkstyle:LineLength")
public enum WhitespaceMode {
    /**
     * Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
     */
    Normalized("normalized"),
    /** Preserve all whitespace exactly as it appears in the HTML. */
    Strict("strict");

    /** The string value. */
    private final String value;

    WhitespaceMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static WhitespaceMode fromValue(final String value) {
        for (WhitespaceMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
