// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d2ed1a6bd0518253f80739100044c054711a666c9d1127759bcc8bba5577ef2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whitespace handling strategy during conversion.
 *
 * Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
 */
@SuppressWarnings("PMD")
public enum WhitespaceMode {
    /**
     * Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
     */
    Normalized("normalized"),
    /**
     * Preserve all whitespace exactly as it appears in the HTML.
     */
    Strict("strict");


    /** The string value. */
    private final String value;

    WhitespaceMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static WhitespaceMode fromValue(final String value) {
        for (WhitespaceMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown WhitespaceMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
