// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44325cfba3fdc518c5ee361aa97eade5d3d093cb472be5261e36121ba41f363d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:h2m/h2m.dart';
import 'package:h2m/src/h2m_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: smoke
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Empty string produces empty output', () async {
    final result = await H2mBridge.convert('');
    expect(result.content, equals(''));
  });

  test('H1 heading converts to ATX markdown', () async {
    final result = await H2mBridge.convert('<h1>Title</h1>');
    expect(result.content, contains('# Title'));
  });

  test('Simple paragraph converts correctly', () async {
    final result = await H2mBridge.convert('<p>Hello World</p>');
    expect(result.content, equals('Hello World'));
    expect(result.content, isNotNull);
  });

}
