<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:120f46e2343431361d3a6c804f433935878e00960d289cb9d00d4ae834e8e6a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);


// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../packages/php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
